Fix MSVC template demangling with ref to mangled symbol
radareorg/radare2 pull request #17601
Opened 2020-09-06 01:48 UTC by GustavoLCR

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

* Also fix not adding the template name as an abbreviation
* Add test

**Test plan**

Tests pass

2020-09-09 14:12 UTC, ret2libc approved these changes
Honestly, I haven't looked at each line, but... the changes look reasonable, tests pass and there is a new test for the fixed case, so I'm pretty much ok with this :)

2020-09-09 18:20 UTC, trufae requested changes

2020-09-09 18:20 UTC, trufae commented on libr/bin/mangling/microsoft_demangle.c
> +int get_namespace_and_name(char *buf, STypeCodeStr *type_code_str, unsigned int *amount_of_names, bool memorize);
this should be static i think

2020-09-09 18:20 UTC, trufae commented on libr/bin/mangling/microsoft_demangle.c
> +int get_namespace_and_name(char *buf, STypeCodeStr *type_code_str, unsigned int *amount_of_names, bool memorize);
use size_t instead of unsigned int

2020-09-09 18:20 UTC, trufae commented on libr/bin/mangling/microsoft_demangle.c
> +int get_namespace_and_name(char *buf, STypeCodeStr *type_code_str,
not sure if char *buf can be const char *buf, and also the return could be bool

2020-09-09 18:20 UTC, trufae commented on libr/bin/mangling/microsoft_demangle.c
> +	case letter: {                                   \
dont indent the backslashes

2020-09-09 18:20 UTC, trufae commented on libr/bin/mangling/microsoft_demangle.c
> +		if (access_modifier) *access_modifier = modifier_str; \
add braces around the if statements, its not needed for the case

2020-09-09 18:20 UTC, trufae commented on libr/bin/mangling/microsoft_demangle.c
> +	unsigned int is_abbr_type = 0;
size_t

2020-09-09 18:20 UTC, trufae commented on libr/bin/mangling/microsoft_demangle.c
> +static EDemanglerErr parse_microsoft_mangled_name(char *sym, char **demangled_name) {
const char *sym i think

2020-09-09 18:20 UTC, trufae commented on libr/bin/mangling/microsoft_demangle.c
> +	len = get_namespace_and_name (curr_pos, &type_code_str, &i, false);
assign and define in the same line

2020-09-10 04:09 UTC, XVilka approved these changes

2020-09-13 20:38 UTC, merged