Fix multiple bugs in matching ##signatures
radareorg/radare2 pull request #17607
Opened 2020-09-08 02:26 UTC by swoops

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [x] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

This refactors out multiple bugs in the matching of signatures. When a signature is matched, the `fcnMatchCB` or `searchHitCB` is called. This previous lead to `addFlag` where there were a few bugs. These bugs prevented the function from being renamed or types applied.

There is still a bug where types are not applied because the `RSignItem` passed to `searchHitCB` does not have a `types` member. This is due to a bug in `r_sign_item_dup` and is addressed in another PR.

**Test plan**
```
$ r2 static 
 -- Did you know that radare2 can decompile to assembly?
[0x00401c60]> s 0x0041dec0
[0x0041dec0]> af
[0x0041dec0]> afs
void fcn.0041dec0 (int64_t arg1);
[0x0041dec0]> zo ./out.sdb 
[0x0041dec0]> z*
zs *
za sym.__strdup b f30f1efa4154554889fd4883ec08e83d69f9ff4c8d60014c89e7e8d167f9ff4885c074154883c4084c89e24889ee4889c75d415ce98769f9ff5a31c05d415cc3:ffffffffffffffffffffffffffffff00000000ffffffffffffffff00000000ffffffff00ffffffffffffffffffffffffffffffffff00000000ffffffffffffff
za sym.__strdup g cc=2 nbbs=3 edges=3 ebbs=1 bbsum=64
za sym.__strdup o 0x0008fb30
za sym.__strdup v r110
za sym.__strdup t func.sym.__strdup.args=1 func.sym.__strdup.arg.0="uint32_t,AAAA"
za sym.__strdup h d8b82299783a827712112871062c12f183da2579815bbb644bec13b71fac5618
[0x0041dec0]> z.
[+] searching 0x0041dec0 - 0x0041dfc0
[+] searching function metrics
hits: 1
[0x0041dec0]> afs
void sym.__strdup (uint32_t AAAA);
[0x0041dec0]> 
```
Note: I use `z.` here b/c it is fast and easy to show. This PR alone won't make `z.` assign types correctly because of the other bug mentioned above. 
**Closing issues**

...

2020-09-08 08:07 UTC, ret2libc commented on libr/core/cmd_zign.c
> +	r_str_remove_char (alltypes, "\"");
```suggestion
	r_str_remove_char (alltypes, '"');
```

2020-09-08 08:08 UTC, ret2libc commented on libr/core/cmd_zign.c
> +			char tmp = r_name_filter2 (name);
```suggestion
			char *tmp = r_name_filter2 (name);
```

2020-09-09 14:16 UTC, ret2libc commented on libr/core/cmd_zign.c
> +static bool apply_name(RCore *core, RAnalFunction *fcn, RSignItem *it, bool rad) {
the return value is never used and it's always true. just return void.

2020-09-09 14:16 UTC, ret2libc commented on libr/core/cmd_zign.c
> +static bool apply_types(RCore *core, RAnalFunction *fcn,  RSignItem *it) {
also here

2020-09-09 14:18 UTC, ret2libc commented
How can I reproduce the test case? Could you provide this "static" binary at least here.

2020-09-09 23:50 UTC, swoops commented
Using `ls` from the test repo

```r2 bins/elf/ls
 -- I love gradients.
 [0x00005ae0]> s 0x00012580
[0x00012580]> af
[0x00012580]> afs
void fcn.00012580 (int64_t arg1);
[0x00012580]> zo /tmp/test.sdb 
[0x00012580]> z.
[+] searching 0x00012580 - 0x00012680
[+] searching function metrics
hits: 2
[0x00012580]> afs
void sym.renamed_value (int64_t AAAA);
[0x00012580]> z* ~ t 
za sym.renamed_value t func.sym.renamed_value.args=1 func.sym.renamed_value.arg.0="int64_t,AAAA"
```

I am attaching the .sdb file as a zip. Sadly you can't add the signature with za because of another bug I am working on fixing. Once that is fixed I should be able to add very simple regression tests for this.

2020-09-10 07:41 UTC, ret2libc approved these changes
Thanks!

2020-09-10 08:28 UTC, trufae requested changes
imho it will better to check for errors in the callers than returning void

2020-09-10 08:28 UTC, trufae commented on libr/core/cmd_zign.c
>  	r_return_val_if_fail (core && fcn && it && it->name, false);
how to return a val if its void

2020-09-10 08:28 UTC, trufae commented on libr/core/cmd_zign.c
>  	r_return_val_if_fail (core && fcn && it && it->name, false);
same here

2020-09-10 18:32 UTC, swoops commented on libr/core/cmd_zign.c
> +		r_list_append (types, r_str_new (r_str_word_get0 (args0, i)));
I will use strdup. There is some other problems with that code which may require it to be changed more substantially.

2020-09-13 20:39 UTC, trufae approved these changes

2020-09-13 21:11 UTC, merged

2020-09-13 21:12 UTC, trufae commented
Damn, I think it will be good to have some tests for those fixes. Can you make a separte PR for them? Thanks