Early support modern imacos
radareorg/radare2 pull request #17611
Opened 2020-09-08 12:45 UTC by mrmacete

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

This change adds early support for "modern" i/macOS, in particular:

- add support for macOS arm64 xnu kernel caches, the ones with the `MH_FILESET` format; this also add preliminary support for chained fixups, used in arm64e mach-O binaries
- add support for iOS 14.x dyld shared caches, with support for multiple rebase info and extra RW mappings
- add support for recent changes to Objective-C, in particular the "small" method lists, in which pointers to method's name, implementation and types are expressed as 32-bit relative offsets instead of absolute 64-bit pointers

I decided to do all the changes in a single PR because they're all inter-dependent.

2020-09-08 13:31 UTC, trufae requested changes
Cool :DD

2020-09-08 13:31 UTC, trufae commented on libr/bin/format/mach0/mach0.c
> +static bool parse_chained_fixups (struct MACH0_(obj_t) *bin, ut32 offset, ut32 size) {
drop the space before ( here

2020-09-08 13:31 UTC, trufae commented on libr/bin/format/mach0/mach0.c
> +	if (size < sizeof(header)) {
add the space before (header

2020-09-08 13:31 UTC, trufae commented on libr/bin/format/mach0/mach0_defines.h
> +/* WARNING: this is guesswork based on trial and error */
ouch :D

2020-09-08 13:31 UTC, trufae commented on libr/bin/p/bin_xnu_kernelcache.c
> +
empty line

2020-09-08 13:31 UTC, trufae commented on libr/bin/p/bin_xnu_kernelcache.c
> +	for (i = 0; i < ncmds && cursor < length; i++) {
use size_t for i.. well read_le32 returns ut32.. so that will work too

2020-09-08 13:31 UTC, trufae commented on libr/bin/p/bin_xnu_kernelcache.c
> +				free(padded_name);
empty space before (

2020-09-08 13:31 UTC, trufae commented on libr/bin/p/bin_xnu_kernelcache.c
> +
empty lines

2020-09-08 13:31 UTC, trufae commented on libr/bin/p/bin_xnu_kernelcache.c
> +		}
bad indent

2020-09-08 13:31 UTC, trufae commented on libr/bin/p/bin_xnu_kernelcache.c
> +	if (!mach0) {
return macho

2020-09-08 13:31 UTC, trufae commented on libr/bin/p/bin_xnu_kernelcache.c
> +	int i = 0;
size_t

2020-09-08 13:31 UTC, trufae commented on libr/bin/p/bin_xnu_kernelcache.c
> +				free(padded_name);
space

2020-09-08 13:31 UTC, trufae commented on libr/bin/p/bin_xnu_kernelcache.c
> +		int i;
sizet

2020-09-08 14:09 UTC, mrmacete commented
fixed the issues and squashed the commits

2020-09-08 16:03 UTC, trufae approved these changes

2020-09-10 04:00 UTC, XVilka commented
Is it possible to add a minimized tests for these somehow?

2020-09-10 16:29 UTC, XVilka commented
Amazing, thanks!

2020-09-10 20:39 UTC, mrmacete commented
working on the test cases, figured out something's off with ivars, hold on

2020-09-11 09:59 UTC, mrmacete commented
It turns out the ivar issue was already there, added new tests and updated the old ones as well.

2020-09-11 10:20 UTC, trufae commented
Amazing! Good work!

2020-09-11 12:39 UTC, mrmacete commented
ok. now that's weird

2020-09-11 12:48 UTC, mrmacete commented
maybe i should just rebase this?

2020-09-13 20:36 UTC, merged