Implement tms320.pseudo to fix another arm64 test ##asm
radareorg/radare2 pull request #17613
Opened 2020-09-08 13:15 UTC by trufae

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

**Closing issues**

fixes this:

```
[XX] db/anal/tms320.c64x_32 320c64 OPEX
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'e asm.arch=tms320
e asm.cpu=c64x
wx 0041bd10
aoj~{}
' malloc://512280
-- stdout
@@ -2,7 +2,7 @@
   {
     "opcode": "b 0x20de8",
     "disasm": "b 0x20de8",
-    "pseudo": "b 0x20de8 ",
+    "pseudo": "jmp 0x20de8",
     "mnemonic": "b",
     "mask": "ff000000",
     "jump": 134632,
```

2020-09-08 13:21 UTC, trufae commented
@XVilka can you provide some feedback in here? i dont know much about tms320

2020-09-08 14:04 UTC, ret2libc commented
Why all this parse plugin is needed when the test works when not on arm64?

2020-09-08 16:04 UTC, trufae commented
The test doesnt work on arm64. The reason is because asm.parser is not updated becvause the plugin doesnt exist. This results in pd using arm.pseudo plugin, which replaces the `b` tms instruction following the arm64 semantics, which is arm64 specific and the test works on x86 just because `b` is not an x86 instruction

2020-09-08 16:17 UTC, ret2libc commented
> which is arm64 specific and the test works on x86 just because b is not an x86 instruction

I see, thanks for the explanation.

2020-09-09 02:48 UTC, XVilka commented
Please fix Meson build:
```
FAILED: libr/anal/04634f8@@r_anal@sha/anal.c.o 
gcc -Ilibr/anal/04634f8@@r_anal@sha -I. -I../ -I../libr/include -I../libr/anal/arch/gb -I../libr/anal/arch/hexagon -I../shlr/spp -I../shlr/sdb/src -I../shlr/zip/zlib -Ilibr/asm/../../shlr -I../libr/asm/../../shlr -I../libr/asm/arch/include -I../libr/asm/arch -I../libr/asm/arch/h8300 -I../libr/asm/arch/hexagon -I../libr/asm/arch/msp430 -I../libr/asm/arch/rsp -I../libr/asm/arch/mcore -I../libr/asm/arch/v850 -I../libr/asm/arch/propeller -I../libr/asm/arch/ebc -I../libr/asm/arch/cr16 -I../libr/asm/arch/8051 -I../libr/asm/arch/v810 -I../libr/asm/arch/or1k -I../shlr/java -I../shlr/capstone/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -fvisibility=hidden -fPIC -pthread -DR2_PLUGIN_INCORE=1 -MD -MQ 'libr/anal/04634f8@@r_anal@sha/anal.c.o' -MF 'libr/anal/04634f8@@r_anal@sha/anal.c.o.d' -o 'libr/anal/04634f8@@r_anal@sha/anal.c.o' -c ../libr/anal/anal.c
In file included from ../libr/anal/anal.c:7:0:
./config.h:20:1091: error: ‘r_anal_plugin_tms320_cs’ undeclared here (not in a function); did you mean ‘r_anal_plugin_tms320’?
 #define R_ANAL_STATIC_PLUGINS &r_anal_plugin_6502, &r_anal_plugin_8051, &r_anal_plugin_amd29k, &r_anal_plugin_arc, &r_anal_plugin_arm_cs, &r_anal_plugin_arm_gnu, &r_anal_plugin_avr, &r_anal_plugin_bf, &r_anal_plugin_chip8, &r_anal_plugin_cr16, &r_anal_plugin_cris, &r_anal_plugin_dalvik, &r_anal_plugin_ebc, &r_anal_plugin_gb, &r_anal_plugin_h8300, &r_anal_plugin_hexagon, &r_anal_plugin_i4004, &r_anal_plugin_i8080, &r_anal_plugin_java, &r_anal_plugin_m68k_cs, &r_anal_plugin_m680x_cs, &r_anal_plugin_malbolge, &r_anal_plugin_mcore, &r_anal_plugin_mips_cs, &r_anal_plugin_mips_gnu, &r_anal_plugin_msp430, &r_anal_plugin_nios2, &r_anal_plugin_null, &r_anal_plugin_or1k, &r_anal_plugin_pic, &r_anal_plugin_ppc_cs, &r_anal_plugin_ppc_gnu, &r_anal_plugin_propeller, &r_anal_plugin_riscv, &r_anal_plugin_rsp, &r_anal_plugin_sh, &r_anal_plugin_snes, &r_anal_plugin_sparc_cs, &r_anal_plugin_sparc_gnu, &r_anal_plugin_sysz, &r_anal_plugin_tms320, &r_anal_plugin_tricore, &r_anal_plugin_v810, &r_anal_plugin_v850, &r_anal_plugin_vax, &r_anal_plugin_wasm, &r_anal_plugin_ws, &r_anal_plugin_x86_cs, &r_anal_plugin_tms320_cs, &r_anal_plugin_xap, &r_anal_plugin_xcore_cs, &r_anal_plugin_xtensa, &r_anal_plugin_z80, 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ^
../libr/anal/anal.c:12:2: note: in expansion of macro ‘R_ANAL_STATIC_PLUGINS’
  R_ANAL_STATIC_PLUGINS
  ^~~~~~~~~~~~~~~~~~~~~
[884/1530] Linking target libr/asm/libr_asm.so.4.6.0-git.
```

2020-09-10 10:03 UTC, ret2libc requested changes

2020-09-10 10:03 UTC, ret2libc commented on libr/parse/p/parse_tms320_pseudo.c
> +			strncpy (w0, buf, sizeof (w0) - 1);
`r_str_ncpy` here and in all other places instead of `strncpy`

2020-09-10 10:03 UTC, ret2libc commented on libr/parse/p/parse_tms320_pseudo.c
> +		if (ptr) {
can we have a small comment before this big chunk of code that explains a little bit how the text is supposed to be transformed? Something like:
```
// Convert "mov rax, [rip + 123213]" into "mov rax, mysuperflag"
```

2020-09-16 14:34 UTC, trufae commented
I added more instructions as well as read and referenced the arch documentation

2020-09-16 18:24 UTC, trufae commented
@XVilka this pr is now ready to be merged imho. its not covering all the tms320 instructions but at least its fixing a bug in non-intel runs for the testsuite, and i spotted a segmentation fault in the avr parser (which is where this parser comes from) i will fix the other parsers later, but i would prefer to have u improving this PR after being merged adding more pseudo disassembly for it.

btw i also found more bugs in the tms320 asm plugin. but they are not related to this pr

2020-09-17 07:48 UTC, ret2libc requested changes

2020-09-17 07:48 UTC, ret2libc commented on libr/parse/p/parse_tms320_pseudo.c
> +		r_str_ncpy (w0, buf, sizeof (w0) - 1);
```suggestion
		r_str_ncpy (w0, buf, sizeof (w0));
```

2020-09-17 07:48 UTC, ret2libc commented on libr/parse/p/parse_tms320_pseudo.c
> +			r_str_ncpy (w2, ptr, sizeof (w2) - 1);
```suggestion
			r_str_ncpy (w2, ptr, sizeof (w2));
```

2020-09-17 07:48 UTC, ret2libc commented on libr/parse/p/parse_tms320_pseudo.c
> +				r_str_ncpy (w3, ptr2 + 1, sizeof (w3) - 1);
```suggestion
				r_str_ncpy (w3, ptr2 + 1, sizeof (w3));
```

2020-09-17 07:48 UTC, ret2libc commented on libr/parse/p/parse_tms320_pseudo.c
> +				*ptr2 = 0;
Just for consistency with all the others you have done here.
```suggestion
				*ptr2 = '\0';
```

2020-09-17 07:48 UTC, ret2libc commented on libr/parse/p/parse_tms320_pseudo.c
> +			strncpy (w1, optr, sizeof (w1) - 1);
```suggestion
			r_str_ncpy (w1, optr, sizeof (w1));
```

2020-09-17 07:48 UTC, ret2libc commented on libr/parse/p/parse_tms320_pseudo.c
> +			ptr = (char*)r_str_trim_head_ro (ptr);
```suggestion
			ptr = (char *)r_str_trim_head_ro (ptr);
```

2020-09-17 07:48 UTC, ret2libc commented on libr/parse/p/parse_tms320_pseudo.c
> +		r_str_ncpy (w1, ptr, sizeof (w1) - 1);
```suggestion
		r_str_ncpy (w1, ptr, sizeof (w1));
```

2020-09-17 07:48 UTC, ret2libc commented on libr/parse/p/parse_tms320_pseudo.c
> +		r_str_ncpy (w0, buf, sizeof (w0) - 1);
```suggestion
		r_str_ncpy (w0, buf, sizeof (w0));
```

2020-09-17 07:48 UTC, ret2libc commented on libr/parse/p/parse_tms320_pseudo.c
> +	if (!(buf = malloc (len + 1))) {
I think a `strdup` here is enough instead of malloc + memcpy.

2020-09-17 07:48 UTC, ret2libc commented on libr/parse/p/parse_tms320_pseudo.c
> +	if (!strncmp (data, "|| ", 2)) {
Considering in the line below you are doing `data += 3`, I think you meant:
```suggestion
	if (!strncmp (data, "|| ", 3)) {
```

2020-09-17 07:48 UTC, ret2libc commented on libr/parse/p/parse_tms320_pseudo.c
> +		r_str_ncpy (w0, buf, sizeof (w0) - 1);
By the way, this is very likely not even needed and a simple `strcpy` would be enough, given that `buf` can be at most `len+1` bytes and `len` is guaranteed to be less than `sizeof(w0)`.

2020-09-17 07:48 UTC, ret2libc commented on libr/parse/p/parse_tms320_pseudo.c
> +	int i, len = strlen (data);
```suggestion
	size_t i, len = strlen (data);
```

2020-09-17 07:48 UTC, ret2libc commented on libr/parse/p/parse_tms320_pseudo.c
> +	int nw = 0;
```suggestion
	size_t nw = 0;
```

2020-09-17 12:13 UTC, trufae commented
There are still some remaining instructions and a bug parsing instructions of 4 arguments. i will that today and add tests imho tests are better than comments

2020-09-17 14:44 UTC, trufae commented
Ready to review and merge now if green

2020-09-17 14:44 UTC, trufae commented
I fixed the instruction parsing and added a test.. using an x86 binary.. couldnt find any tms file

2020-09-18 07:21 UTC, ret2libc reviewed
Code looks much better now! Let's wait for @XVilka to come back and have a look

2020-09-21 03:50 UTC, XVilka approved these changes

2020-09-21 03:51 UTC, merged