Fix #17638 - set protocol to TCP in HTTP server ##remote
radareorg/radare2 pull request #17641
Opened 2020-09-13 13:51 UTC by meme

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] ~~I've added tests that prove my fix is effective or that my feature works (if possible)~~
- [ ] ~~I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)~~

**Detailed description**

See issue.

**Test plan**

See issue.

**Closing issues**

Closes  #17638

2020-09-13 17:30 UTC, trufae approved these changes

2020-09-13 17:56 UTC, trufae commented
Your fix looks better than mine i did a week ago and for some reason forgot to push. i though the issue was fixed already thats why i didnt got what happened...

My pr have some syntax fixes and an extra perror when listen fails. check out the pr i missed a week ago and feel free to apply any of those fixes. ill close my pr after this. https://github.com/radareorg/radare2/pull/17644

also maybe good to have protocol=0 to a meaningful enum name and proper error. because thats the default value at initialization time.

thanks!

2020-09-14 07:36 UTC, ret2libc approved these changes

2020-09-14 17:34 UTC, trufae requested changes

2020-09-14 17:34 UTC, trufae commented on libr/core/rtr_http.c
> +	s->proto = R_SOCKET_PROTO_TCP;
maybe r_socket_new should set TCP as default protocol. because protocl=0 means nothing

2020-09-14 17:34 UTC, trufae commented on libr/socket/socket.c
> +		eprintf ("Error creating socket: did not specify a protocol.");
missing newline at the end of the string

2020-09-15 00:27 UTC, meme commented
Added an `R_SOCKET_PROTO_DEFAULT` and make it default to `TCP` as you suggested, as well added the error condition that you did in your PR.

2020-09-15 09:20 UTC, trufae approved these changes
It's important to get this fix in, despite there are some further changes. This PR fixes the problem and improves the error handling. I will do further refactorings in a separate PR.
Thanks!

2020-09-15 09:22 UTC, merged