Implement touch shell command ##shell
radareorg/radare2 pull request #17645
Opened 2020-09-13 23:45 UTC by trufae

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

2020-09-14 08:10 UTC, ret2libc requested changes
Small test for new command please. LGTM otherwise.

2020-09-14 16:17 UTC, trufae commented
Actually i started to implement a touch api with ut64 timestamps to change the access and creation times of the file in a portable way, but this is out of the scope of this pr. so ill just add the test in here and wait for aprovals

2020-09-14 16:38 UTC, ret2libc commented
> Actually i started to implement a touch api with ut64 timestamps to change the access and creation times of the file in a portable way, but this is out of the scope of this pr. so ill just add the test in here and wait for aprovals

For clarity, I'm asking just about a simple test in `test/db/` that uses `touch` to create the file. We got some code coverage for that path at least.

2020-09-15 07:10 UTC, ret2libc approved these changes

2020-09-15 09:11 UTC, merged