WIP Fix #17039 ##anal ##json
radareorg/radare2 pull request #17661
Opened 2020-09-16 13:00 UTC by mrglm

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

`abj` used to be an alias to `afbj`, nut bow it returns information (in JSON) for only one basic block.

I'm not sure what is the difference between  the properties `addr` and `opaddr` of a basic block, and I did not find documentation about it. Still, I think that the `opaddr`  of a block might be incorrect sometimes, so hit me up if you have information. 

**Test plan**

...

**Closing issues**

Closes #17039

2020-09-16 13:23 UTC, ret2libc commented on libr/core/cmd_anal.c
> +            if (input[2] && input[2] != '.') {
wrong indentation here and in all following lines.

2020-09-23 23:51 UTC, trufae commented
Dupped work with https://github.com/radareorg/radare2/pull/17680

2020-12-09 02:42 UTC, trufae requested changes
What's left to be done to not b e considered WIP?

2020-12-09 02:42 UTC, trufae commented on libr/core/cmd_anal.c
> +				pj_free (pj);
if b or fcn are null pj will never be freed

2020-12-11 13:05 UTC, mrglm commented
There was some work that was a duplicate with another pull request, so I was waiting for this PR to be merged. I'll get back to it and see if there is any work left to be done.

2020-12-11 17:57 UTC, trufae commented
Yeah the other PR got merged, so this one must be rebased, i think moving this logic into a separate function makes sense. about your questions:

* addr = adderss of the basic block holding the current instruction
* opaddr = address of the instruction you are at.

this is.. if you are int he middle of a instruction abj may find the bb by address, and then check the Nth instruction that matches the given offset and provide that info

2020-12-31 21:57 UTC, trufae approved these changes

2020-12-31 21:58 UTC, merged