Rasm2 bits
radareorg/radare2 pull request #17686
Opened 2020-09-21 16:20 UTC by trufae

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

2020-09-22 07:57 UTC, ret2libc requested changes

2020-09-22 07:57 UTC, ret2libc commented on libr/main/rasm2.c
> +				if (h->bits == 0) {
do an `else if` with the line before, no need for another level of indentation.

2020-09-22 08:21 UTC, ret2libc approved these changes

2020-09-23 05:31 UTC, XVilka approved these changes

2020-09-23 05:31 UTC, merged