Always register the derived CC from the reg profile ##anal
radareorg/radare2 pull request #17685
Opened 2020-09-21 15:54 UTC by trufae

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

Some archs lack any definition of calling conventions. In addition, r2 can start without cc defined when running without proper installation or just using the single static binary. This patch registers the derived regprofile right after setting the arch

**Test plan**

this will probably break some tests,so its worth reviewing and updating them to include the new reg profile

**Closing issues**

...

2020-09-21 16:55 UTC, thestr4ng3r requested changes

2020-09-21 16:55 UTC, thestr4ng3r commented on libr/core/cbin.c
> +	r_core_cmd0 (core, "tcc `arcc`");
Are you sure this will never cmd-inject itself? I would rather use api here.

2020-09-21 17:27 UTC, thestr4ng3r commented
lgtm when green

2020-09-21 18:17 UTC, trufae commented
I think the warning gets printed several times in some cases. Maybe its better to remove it. Wait a bit

2020-09-24 15:15 UTC, trufae commented
It's green. can we merge this? (the red is because the http test)

2020-09-24 15:17 UTC, merged