Do not free ds->opstr after r_parse_immtrim
radareorg/radare2 pull request #17728
Opened 2020-09-28 12:17 UTC by ret2libc

There is no new allocation in r_parse_immtrim, so it is not required to
free the "previous" string.

 

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

r_parse_immtrim just moves bytes but it does not allocate a new string, so the free is wrong.

**Test plan**

Run `e asm.imm.trim=true; pd 10` and you will get a double free.

2020-09-29 09:51 UTC, trufae commented
I guess this is causing a segfault somehow? do you have a reproducer? the RParse API needs a redesign too. the current usage/behaviour is not properly defined, and it works.. but functions take so much arguments and its not easy to follow/extend.

2020-09-29 09:56 UTC, ret2libc commented
> I guess this is causing a segfault somehow? do you have a reproducer? the RParse API needs a redesign too. the current usage/behaviour is not properly defined, and it works.. but functions take so much arguments and its not easy to follow/extend.

See the first comment, Test plan:

> Test plan
> 
> Run `e asm.imm.trim=true; pd 10` and you will get a double free.

2020-09-29 10:16 UTC, trufae requested changes
Can you add a test for this? it will be helpful for the rparser refactoring

2020-10-10 10:01 UTC, trufae commented
ping

2020-10-12 09:04 UTC, ret2libc commented
> ping

pong

2020-10-12 15:54 UTC, trufae commented
looks red

2020-10-13 07:27 UTC, XVilka approved these changes

2020-10-13 07:47 UTC, ret2libc commented
> looks red:
> 
> ```
> [XX] db/cmd/cmd_pd asm.imm.trim
> R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 's 0x080483d5
> pi 1 @e:asm.imm.trim=false
> pi 1 @e:asm.imm.trim=true
> ' bins/elf/crackme0x05
> -- stdout
> @@ -1,2 +1,2 @@
>  and esp, 0xfffffff0
> -and esp,
> +and esp, 
> ```

Green now!

2020-10-13 10:16 UTC, trufae approved these changes

2020-10-13 10:40 UTC, merged