Set realname on all bin strings for better asm.flags.real ##disasm
radareorg/radare2 pull request #17774
Opened 2020-10-09 15:45 UTC by trufae

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

before

<img width="423" alt="Screenshot 2020-10-09 at 17 45 06" src="https://user-images.githubusercontent.com/6431515/95603892-30acde00-0a57-11eb-9564-c9c5485db6a3.png">

after

![IMAGE 2020-10-09 17:44:52](https://user-images.githubusercontent.com/6431515/95603849-238fef00-0a57-11eb-948f-ebe26044e0b9.jpg)

**Test plan**

...

**Closing issues**

...

2020-10-09 16:43 UTC, XVilka commented
Didn't check the code, but will it work with the ANSI control characters and hidden Unicode symbols? Like RTL control characters etc?

2020-10-10 18:21 UTC, ITAYC0HEN requested changes
I think it was discussed during the real name refactoring and was decided not to be done. Or to be done via other eval.
I don't remember. 

Requesting changes as a way to block the merge 



@thestr4ng3r, do you remember?

2020-10-10 19:15 UTC, thestr4ng3r commented
Don't remember either. I think the main issue is that it can use a lot of memory.

2020-10-10 20:35 UTC, ret2libc commented
> I think it was discussed during the real name refactoring and was decided not to be done. Or to be done via other eval.
> I don't remember. 
> 
> Requesting changes as a way to block the merge 
> 
> 
> 
> @thestr4ng3r, do you remember? 

I don't remember either

2020-10-11 06:15 UTC, ITAYC0HEN commented
Thinking of Cutter, the rework on Real-Name was, among others, so we can get rid of the annoying prefix for API functions (mostly).
So `call sym.imp.user32.dll_MessageBoxA` will be shown as `call MessageBoxA`. On GUI, you mostly navigate by double-clicking so the visible naming can be truncated, unlike in r2 where you need to copy the name and to `s sym.imp.user32.dll_MessageBoxA`.

Strings are a different story, as they can be huge and messy and not necessarily improve the experience of the user.
I do think that there should be a way to show raw strings in the disassembly but am against having it shown only when `asm.flags.real` is eanbled. Otherwise, I will probably need to think of a way to do another refactoring for this part to improve the output

2020-10-11 08:41 UTC, thestr4ng3r commented
So I guess the better solution will be to add `asm.flags.strings` which will when disassembling check if the flag is in the strings flagspace and try to print the string there.

2020-10-11 16:02 UTC, ITAYC0HEN commented
I am fine with this suggestion :)

2020-10-12 06:30 UTC, XVilka commented
Agree on separation of strings and flags real names show. Thus, as @thestr4ng3r suggested - `asm.flags.strings`.

2020-10-12 06:30 UTC, XVilka requested changes
Agree on separation of strings and flags real names show. Thus, as @thestr4ng3r suggested - `asm.flags.strings`.

2020-10-12 10:03 UTC, trufae commented
the memory issue problem is not triggered by the disasm, the problem is rbin loading those strings multiple times in memory. This can be resolved at runtime by calling a function that gets the string, instead of taking a field from the flagitem. Actually those strings can be built on the fly without taking more memory at load time. ill think on a better solution that doesnt involves consuming more memory. this was just a poc for discussion. thanks for the feedback.

2020-10-12 10:45 UTC, thestr4ng3r commented
> the memory issue problem is not triggered by the disasm, the problem is rbin loading those strings multiple times in memory. This can be resolved at runtime by calling a function that gets the string, instead of taking a field from the flagitem. Actually those strings can be built on the fly without taking more memory at load time.

Yep, that's exactly the proposal. sgtm.

2020-12-03 06:18 UTC, XVilka commented
@trufae could you please update the PR according to @thestr4ng3r proposal?

2020-12-06 17:41 UTC, trufae commented
Yes, but this may require some time, its not a quick fix. And right now i don't have that spare time. Hopefully soon

2020-12-16 13:59 UTC, merged