Fix UB in r_core_cmd_init
radareorg/radare2 pull request #17832
Opened 2020-10-23 17:47 UTC by trufae

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

2020-10-23 18:51 UTC, ret2libc requested changes
There is no UB and no bug. It is just a false positive. `cd` cannot be NULL because all enum values are considered in the switch and if you don't consider all values the compiler spits out a warning about a missing enum value in the switch.

2020-10-26 08:20 UTC, trufae commented
The warning is this:

```
cmd.c: In function 'r_core_cmd_init':
cmd.c:7197:4: warning: 'cd' may be used uninitialized in this function [-Wmaybe-uninitialized]
    cmds[i].descriptor_init (core, cd);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

By reading the code i see that type is an enum so it must be handling all the cases of the switch, so indeed, the cd variable must be initialized.. the problem is that the callbacks can return null, which may result on cd=null, and therefor there's a bug in the call, which is fixed by the `if (cd && `.. about the uniitalized i think its a false positive from the compiler, but i think it doesnt hurts to initialize it

2020-10-26 08:44 UTC, ret2libc approved these changes
`new` can indeed report NULL, right.

2020-10-26 10:33 UTC, XVilka approved these changes

2020-10-26 10:33 UTC, merged