Fix some memory leaks
radareorg/radare2 pull request #17876
Opened 2020-10-29 21:12 UTC by pelijah

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

2020-11-01 00:31 UTC, trufae requested changes

2020-11-01 00:31 UTC, trufae commented on libr/anal/fcn.c
> +				if (bb->cond) {
free functions accept NULL, so you must remove this if()

2020-11-01 00:32 UTC, trufae commented
Also specify where are those memleak fixes in the PR title

2020-11-18 07:09 UTC, XVilka commented
Could you please rebase on top of the master?

2020-11-18 07:09 UTC, XVilka approved these changes

2020-11-19 07:55 UTC, merged