Fix #17878
radareorg/radare2 pull request #17881
Opened 2020-10-30 20:58 UTC by pelijah

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

2020-11-01 01:14 UTC, trufae requested changes

2020-11-01 01:14 UTC, trufae commented on libr/bin/format/coff/coff.c
> +	if (!r_bin_coff_init_scn_va(obj)) {
missing space before (

2020-11-01 01:14 UTC, trufae commented on libr/bin/format/coff/coff.c
> +	if (!r_bin_coff_init_scn_va(obj)) {
```suggestion
	if (!r_bin_coff_init_scn_va (obj)) {
```

2020-11-01 01:14 UTC, trufae requested changes
.

2020-11-01 02:49 UTC, trufae commented
Make the pr title more descriptive

2020-11-01 13:54 UTC, kazarmy commented
Please put `fuzz` in the branch name so that the fuzz tests are run. Even better, put `asanfuzz` so that asan is run on the fuzz tests.

2020-11-02 10:43 UTC, kazarmy approved these changes
Not sure whether this works but let's give it a try!

2020-11-02 10:44 UTC, merged