Fix printing array types inside structs in C format
radareorg/radare2 pull request #17888
Opened 2020-11-01 01:36 UTC by GustavoLCR

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

Half of #17884 fixed

**Test plan**

Tests pass

2020-11-01 02:13 UTC, trufae requested changes

2020-11-01 02:13 UTC, trufae commented on libr/core/cmd_type.c
> +					char *arr = sdb_array_get (TDB, var2, 2, NULL);
arr is leaking.

2020-11-01 02:13 UTC, trufae commented on libr/core/cmd_type.c
> +						if (atoi (arr)) {
what about using %d instead and show the actual parsed number instead of the string which can contain trailing non-numeric chars

2020-11-01 02:13 UTC, trufae commented on libr/core/cmd_type.c
> +							if (atoi (arr)) {
same here. just compute arrnum once

2020-11-01 02:47 UTC, trufae reviewed
If the size is a string it should be printing a warning that dybamic array sizes are not supported. Yet

2020-11-01 10:37 UTC, trufae approved these changes

2020-11-02 04:24 UTC, XVilka approved these changes

2020-11-02 04:24 UTC, merged