Stop trace sessions in the doc command ##debug
radareorg/radare2 pull request #17886
Opened 2020-10-31 22:17 UTC by yossizap

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

Close any existing trace session when stopping debug with `doc` to avoid accidentally starting a new debug session with an existing trace. 

**Test plan**

Run `ood` -> `dts+` -> `doc` and see that `dts-` reports that there's no session

2020-10-31 23:05 UTC, trufae requested changes

2020-10-31 23:05 UTC, trufae commented on libr/core/cmd_debug.c
> +			r_core_cmd0 (core, "dts-");
can you use the API instead of running a command?

2020-11-01 21:34 UTC, trufae approved these changes

2020-11-02 04:24 UTC, XVilka approved these changes

2020-11-02 04:25 UTC, merged