Add x86-16 tests for the operand-size prefix
radareorg/radare2 pull request #17890
Opened 2020-11-02 19:07 UTC by ramikg

In real mode – make sure the operand-size override prefix (0x66) is added when, and only when, necessary.

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [x] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

In x86 real mode, it is possible to access 32-bit registers by prefixing the instruction with 66h. This is exemplified in this PR's commit.
I've added tests that make sure that the operand-size prefix is added when needed, and not added otherwise.

2020-11-11 15:41 UTC, trufae commented
![Screenshot 2020-11-11 at 16 41 36](https://user-images.githubusercontent.com/6431515/98832163-c6fc6700-243c-11eb-9635-4361c0bbdbd7.png)

2020-11-11 18:02 UTC, ramikg commented
Indeed, _asm.nz_ fails the new tests, as it doesn't apply the operand-size prefix correctly (as opposed to _asm.as_ & _asm.nasm_).

Hopefully I'll find the time to go through _asm.nz_'s code.

2020-11-11 18:19 UTC, ramikg commented
Indeed, _asm.nz_ fails the new tests, as it doesn't apply the operand-size prefix correctly (as opposed to _asm.as_ & _asm.nasm_).

I'll open an issue about this.

2020-11-11 19:12 UTC, trufae commented
I would prefer to update this pr to support these indtructions in .nz or mark them as broken as last option. No need to open an issue if you are planning to implement that. Nz code is quite straight forward. Let me know if you have any question.

2020-12-09 02:35 UTC, trufae commented
ping

2021-02-27 01:09 UTC, trufae commented on test/db/asm/x86_16
> +a "sub sp, 2" 83ec02
Use aB instead of a in all those 4 failing tests

2021-02-27 01:09 UTC, trufae requested changes
Use aB instead of a in all those 4 failing tests

2021-02-27 20:15 UTC, ramikg commented
Changed to `aB`, but unfortunately I won't be able to update the PR or open an issue any time soon.

2021-02-27 20:52 UTC, merged