Add internel help for `dmhj` ##cons
radareorg/radare2 pull request #17902
Opened 2020-11-08 10:39 UTC by officialcjunior

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

Internal help for `dmhj` was missing inside the help for `dmh?`. I've added that in this Pull Request.

**Test plan**

See if there's a change which needs to be addressed.

**Closing issues**

None

2020-11-09 11:27 UTC, trufae requested changes

2020-11-09 11:27 UTC, trufae commented on libr/core/linux_heap_glibc.c
> +	"dmh", "", "List the chunks inside heap segment",
inside **the** heap

2020-11-09 11:27 UTC, trufae commented on libr/core/linux_heap_glibc.c
> +	"dmhj", "", "List the chunks inside heap segment in JSON format",
inside **the** heap

2020-11-09 11:29 UTC, officialcjunior commented on libr/core/linux_heap_glibc.c
> +	"dmhj", "", "List the chunks inside heap segment in JSON format",
Sure. Will update in a minute.

2020-11-09 11:38 UTC, officialcjunior commented on libr/core/linux_heap_glibc.c
> +	"dmhj", "", "List the chunks inside heap segment in JSON format",
Fixed. Marking this as resolved.

2020-11-09 11:52 UTC, trufae approved these changes

2020-11-10 05:11 UTC, officialcjunior commented
Hey @XVilka, this one is done. 👍🏻

2020-11-10 05:19 UTC, XVilka approved these changes

2020-11-10 05:19 UTC, merged