Use PJ in `bj` and add tests ##json
radareorg/radare2 pull request #17916
Opened 2020-11-12 09:46 UTC by officialcjunior

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

In this patch, I have used the PJ API for the command `bj` and added tests for both `b` and `bj`. `bj` was previously `printf`-ing the output to STDOUT.

**Test plan**
All the written tests pass without any breaks:
```
$ r2r -Vi test/db/cmd/cmd_b
Running from /home/cjunior/Downloads/programs/radare2/test
Loaded 2 tests.
Skipping json tests because jq is not available.
[OK] /home/cjunior/Downloads/programs/radare2/test/db/cmd/cmd_b bj
[OK] /home/cjunior/Downloads/programs/radare2/test/db/cmd/cmd_b b
[2/2]                       2 OK         0 BR        0 XX        0 FX
Finished in 1 seconds.
```

- [ ]  Request changes if necessary and fix them.

**Closing issues**
Related to #13969

2020-11-13 07:01 UTC, XVilka approved these changes

2020-11-13 08:17 UTC, trufae requested changes

2020-11-13 08:17 UTC, trufae commented on libr/core/cmd.c
> +		PJ * pj = pj_new ();
Check for null

2020-11-13 10:56 UTC, officialcjunior commented on libr/core/cmd.c
> +		PJ * pj = pj_new ();
Would that be enough?

2020-11-23 08:51 UTC, XVilka approved these changes

2020-11-23 08:52 UTC, merged

2020-11-23 09:13 UTC, officialcjunior commented
Thank you,
I have 17642 too, which I think, is also ready to merged.

2020-11-23 09:20 UTC, officialcjunior commented on libr/core/cmd.c
> +		PJ * pj = pj_new ();
Marking as resolved.