Update snes_op_table.h WDM
radareorg/radare2 pull request #17922
Opened 2020-11-15 15:52 UTC by alimansfield2016

WDM is a two byte instruction incorrectly being decoded as a single byte. Modified the table to correct this and updated the format string appropriately.

 

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [x] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

This is a minor change. The `SNES_OP_8BIT` was replaced with `SNES_OP_16BIT`, and the format string was updated to include the operand.

...

**Test plan**

Is it really necessary for such a small change?

...

**Closing issues**

...

2020-11-15 16:08 UTC, trufae commented
Can you add some tests for the SNES disassembler?

2020-11-15 16:32 UTC, wargio requested changes
Missing tests.

2020-11-29 00:22 UTC, trufae approved these changes

2020-11-29 00:24 UTC, merged

2020-11-29 01:02 UTC, trufae commented
I wrote some tests for snes https://github.com/radareorg/radare2/pull/17988