##projects ##refactor project.c: Changed Camel To Snake Case And Used Macros In is_valid_project_name()
radareorg/radare2 pull request #18101
Opened 2020-12-23 13:35 UTC by RHL120

**Checklist**

- [] Closing issues: #issue
- [x] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [radare2book](https://github.com/radareorg/radare2book)

**Description**
I tried to check if I renamed all camel case variables properly but you should propbaly double check weather or not I gave a variable a stupid name. I used the macros IS_UPPER and IS_LOWER in is_valid_project_name()

2020-12-23 16:29 UTC, trufae requested changes

2020-12-23 16:29 UTC, trufae commented on libr/core/project.c
> +		if (IS_LOWER(name[i]) || IS_UPPER(name[i])) {
space before (

2020-12-23 16:29 UTC, trufae commented on libr/core/project.c
> +static inline void remove_notes_file(char *pd) {
const char *pd

2020-12-23 16:29 UTC, trufae commented on libr/core/project.c
> +static inline void remove_rop_directory(char *prj_dir) {
const char*

2020-12-23 16:29 UTC, trufae commented on libr/core/project.c
> +	if (!prj_name || !*prj_name) {
use r_return_val_if_fail instead

2020-12-23 21:29 UTC, trufae commented on libr/core/project.c
> +	r_return_val_if_fail (false, prj_name || *prj_name);
Should be &&

2020-12-23 22:09 UTC, trufae requested changes

2020-12-23 22:09 UTC, trufae commented on libr/core/project.c
> +		if (IS_LOWER (name[i]) || IS_UPPER (name[i])) {
if (isalpha(name[i]))

2020-12-23 22:09 UTC, trufae commented on libr/core/project.c
> +	project_state *ps = R_NEW0 (project_state);
dont snakecase the types. ProjectState is fine

2020-12-23 22:09 UTC, trufae commented on libr/core/project.c
> +
empty line

2020-12-24 08:36 UTC, trufae commented
Still red

2020-12-24 12:59 UTC, RHL120 commented
> Still red

Yeah I think I know why that happend. Sorry for being an idiot

2020-12-24 15:30 UTC, trufae commented
Mistakes happen. You should try harder to become an idiot :) seems like this wasnt yet the reason for the ci to be red 🤔

2020-12-26 10:36 UTC, merged