FIX some bugs in dex.c, marshal.c, panels.c and other code optimization and fixel
radareorg/radare2 pull request #18297
Opened 2021-01-26 21:33 UTC by ChD1

**Checklist**

- [ ] Closing issues: #issue
- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [radare2book](https://github.com/radareorg/radare2book)

**Description**

2021-01-26 23:21 UTC, trufae commented on libr/main/rabin2.c
> +			if(r){
```suggestion
			if (r) {
```

2021-01-26 23:22 UTC, trufae commented on libr/core/panels.c
> +	if(!p){
```suggestion
	if (!p) {
```

2021-01-26 23:22 UTC, trufae commented on libr/core/panels.c
> +	if(!p){
```suggestion
	if (!p) {
```

2021-01-26 23:23 UTC, trufae commented on libr/core/panels.c
> +	if(!panel){
```suggestion
	if (!panel) {
```

2021-01-26 23:23 UTC, trufae commented on libr/core/panels.c
> +	if(!p){
```suggestion
	if (!p) {
```

2021-01-26 23:23 UTC, trufae commented on libr/core/panels.c
> +	if(!panel){
```suggestion
	if (!panel) {
```

2021-01-26 23:23 UTC, trufae commented on libr/core/panels.c
> +	if(!panel){
```suggestion
	if (!panel) {
```

2021-01-26 23:25 UTC, trufae commented on libr/core/vmenus.c
> +					if(r){
just call free (r); the if is unnecessary

2021-01-26 23:25 UTC, trufae commented on libr/core/vmenus.c
> +						free(r);
same here

2021-01-26 23:26 UTC, trufae commented on libr/main/rabin2.c
> +			if (r) {
same here

2021-01-26 23:27 UTC, trufae requested changes
Please git pull the commits i pushed before addressing the comments. free(NULL) is valid, so there's no need to wrap it with an if()

2021-01-27 00:39 UTC, trufae requested changes
Please use tabs

2021-01-27 00:39 UTC, trufae commented on libr/main/radare2.c
> +                free (debugbackend);
bad indentation. use tabs

2021-01-27 00:39 UTC, trufae commented on libr/main/radare2.c
> +            free (debugbackend);
use tabs

2021-01-27 00:39 UTC, trufae commented on libr/main/rahash2.c
> +                    if (str != hashstr) {
use tabs

2021-01-27 00:39 UTC, trufae commented on libr/util/pkcs7.c
> +            free (container);
use tabs

2021-01-27 00:39 UTC, trufae commented on libr/core/linux_heap_glibc.c
> +        free (cnk);
use tabs

2021-01-27 00:39 UTC, trufae commented on libr/cons/pal.c
> +            if (r) {
unnecessary if

2021-01-27 00:39 UTC, trufae commented on libr/core/anal_tp.c
> +        free (buf);
use tabs

2021-01-27 00:39 UTC, trufae commented on libr/core/cmd_debug.c
> +                    free (name);
tabs

2021-01-27 00:39 UTC, trufae commented on libr/core/cmd_open.c
> +			} else {
tabs

2021-01-27 08:42 UTC, ChD1 commented on libr/core/cmd_open.c
> +			} else {
All done.

2021-01-27 08:45 UTC, trufae commented
Fix the warning to make the ci happy
![470DAE1F-192C-4090-9A6B-F6BAC08D803A](https://user-images.githubusercontent.com/6431515/105965992-5d2b4b00-6084-11eb-87d2-765862141283.jpeg)

2021-01-27 09:12 UTC, ChD1 commented
Done. I think.

2021-01-27 09:53 UTC, merged

2021-01-27 09:54 UTC, trufae commented
Perfect!! Good findings!