FIXes some fixes
radareorg/radare2 pull request #18307
Opened 2021-01-28 19:09 UTC by ChD1

**Checklist**

- [ ] Closing issues: #issue
- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [radare2book](https://github.com/radareorg/radare2book)

**Description**

2021-01-28 20:32 UTC, trufae requested changes
.

2021-01-28 20:32 UTC, trufae commented on libr/core/panels.c
> +		if (!panel) continue;
please follow the coding style guide. there are no single line ifs. always add braces and a newline

2021-01-28 20:32 UTC, trufae commented on libr/core/panels.c
>  		if (!strncmp (p->model->cmd, help, strlen (help))) {
if (p && !strcmp ...) looks better to me

2021-01-28 20:32 UTC, trufae commented on libr/core/panels.c
>  		if (p->view->pos.x == 0) {
same

2021-01-28 20:52 UTC, ChD1 commented on libr/core/panels.c
>  		if (p->view->pos.x == 0) {
done

2021-01-29 18:47 UTC, trufae approved these changes

2021-01-29 18:49 UTC, merged