V850 jmptable fix, cmpval is almost always -1 and slows anal to a crawl
radareorg/radare2 pull request #18498
Opened 2021-03-20 00:08 UTC by brainstorm

- [ ] Closing issues: #issue
- [x] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [radare2book](https://github.com/radareorg/radare2book)

**Description**

@trufae's jmptable PR https://github.com/radareorg/radare2/pull/18447 examines the whole memory and sprinkles the asm listing with many false `case`s:

<img width="387" alt="Screen Shot 2021-03-20 at 11 07 22 am" src="https://user-images.githubusercontent.com/175587/111852792-74900180-896c-11eb-8e32-b27587dfd085.png">

This PR mitigates this bad side effect but needs further work to fix.

2021-03-20 00:39 UTC, trufae requested changes
we can probably remove the line computing ptsz above too. Maybe we can also track the cmpaddr and avoid taking into account far cmp instructions

2021-03-20 00:39 UTC, trufae commented on libr/anal/fcn.c
> +				if (cmpval!= -1){
```suggestion
				if (cmpval > 0) {
```

2021-03-20 23:56 UTC, brainstorm commented
> we can probably remove the line computing ptsz above too

And just pass `cmpval` to `try_walktrhough_jmptbl` instead of ptsz?

2021-03-21 00:00 UTC, brainstorm commented
> Maybe we can also track the cmpaddr and avoid taking into account far cmp instructions

How does one determine what is far and near in the context of V850 jumps? Jumping more than X opcodes where X is...?

2021-03-21 01:27 UTC, trufae approved these changes

2021-03-21 01:27 UTC, merged

2021-03-21 01:27 UTC, trufae commented
Let's merge for now, we can improve that jmptbl analysis later. Thanks!

2021-03-21 01:59 UTC, trufae commented
Lets say thebdistance can be a constant.. i didnt saw thst cmp farther than 32 bytes and i bet there could be nested switches too