Add Levenshtiend path API to ##diff
radareorg/radare2 pull request #18494
Opened 2021-03-18 18:18 UTC by swoops

**Checklist**

- [ ] Closing issues: #issue
- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [radare2book](https://github.com/radareorg/radare2book)

**Description**
I did not see a way to get the changes from a Levenshtien algorithm in r2, so I made it.

This pull ads a the function `r_diff_levenshtein_path`. Like `r_diff_buffers_distance_levenshtein` this function computes the Levenshtien distance. Unlike `r_diff_buffers_distance_levenshtein` it produces enough of the matrix to return a `RLEVEND` terminated array of changes that can be used to get from one buffer to the other. So this is not a replacement for `r_diff_buffers_distance_levenshtein`. This is only helpful if you want to display where difference in buffers occur, and what those differences are, rather then how many difference occur.

Currently nothing in r2 uses this function yet. I hope to use it for diffing signatures to help debug why a signature does not match. Thus the capability to include a mask in the buffer comparison. 

I am not sure I am putting this code in the proper place, naming things well or using proper types. So I figured I would submit it for review now.

### About the alg:
Since Levenshtien is expensive in memory, a `maxdst` parameter is accepted. When this value is small, the algorithm can allocate much smaller rows for the matrix. Also, by watching when a change must occur between rows, we can make smaller allocations on later rows. If the provided `maxdist` is not large enough, the function returns ST32_MAX as the distance and the array of changes is left pointing at `NULL`. Errors, such as memory alloc fails, will result in returning -1.

### fuzzing it
Since this alg is a bit tricky, I threw a differential fuzzing harness together and let AFL attack it. The harness aborts if distance returned by `r_diff_buffers_distance_levenshtein` differs from the returned distance of `r_diff_levenshtein_path`. This is verified both for `r_diff_levenshtein_path` with a maximum `maxdist` and a minimum `maxdist` (ie: `maxdist` set to actual distance). The harness will also abort if the array of changes from `r_diff_levenshtein_path` vary depending on `maxdist` minimum/maximum. The harness will also abort if a provided `maxdist` one less then minimum does not exit correctly. After 400M+ iterations there were no crashes or hangs. I will upload the fuzzing harness if you would like to see it.

## Debug output to show how memory is saved
With no provided max distance, `abcdefg` vs `XabcdefgX` saves only one cell of memory b/c only one change happens early:
```
       58 61 62 63 64 65 66 67 58
    00 01 02 03 04 05 06 07 08 09  buflen: 10
61  01 01 01 02 03 04 05 06 07 08  buflen: 10
62  02 02 02 01 02 03 04 05 06 07  buflen: 10
63  03 03 03 02 01 02 03 04 05 06  buflen: 10
64  04 04 04 03 02 01 02 03 04 05  buflen: 10
65  05 05 05 04 03 02 01 02 03 04  buflen: 10
66  06 06 06 05 04 03 02 01 02 03  buflen: 10
67  .. 07 07 06 05 04 03 02 01 02  buflen: 9

79 matrix cells allocated
distance: 2
     ++   X  changes: 1
  a  ==   a  changes: 1
  b  ==   b  changes: 1
  c  ==   c  changes: 1
  d  ==   d  changes: 1
  e  ==   e  changes: 1
  f  ==   f  changes: 1
  g  ==   g  changes: 1
     ++   X  changes: 2
```

Same input as above but with a `maxdist` of 2 results in rows being allocated with fewer cells. 27 total cells here, 79 above. What is computed in the matrix here agrees with the one above. Cells occupied by `..` represents cells that were never computed or allocated. Those cells are not reachable taking a path through the matrix that only uses 2 changes.
```
       58 61 62 63 64 65 66 67 58
    00 01 02 03 04 .. .. .. .. ..  buflen: 5
61  .. 01 01 02 03 04 .. .. .. ..  buflen: 5
62  .. .. .. 01 02 03 .. .. .. ..  buflen: 3
63  .. .. .. .. 01 02 03 .. .. ..  buflen: 3
64  .. .. .. .. .. 01 02 03 .. ..  buflen: 3
65  .. .. .. .. .. .. 01 02 03 ..  buflen: 3
66  .. .. .. .. .. .. .. 01 02 03  buflen: 3
67  .. .. .. .. .. .. .. .. 01 02  buflen: 2

27 matrix cells allocated
distance: 2
...
```

We can still save a modest amount of memory without knowing the distance ahead of time if many changes occur early. 
```
       41 42 43 44 45 46 47 48 49 4a 4b
    00 01 02 03 04 05 06 07 08 09 0a 0b  buflen: 12
61  01 01 02 03 04 05 06 07 08 09 0a 0b  buflen: 12
62  02 02 02 03 04 05 06 07 08 09 0a 0b  buflen: 12
63  03 03 03 03 04 05 06 07 08 09 0a 0b  buflen: 12
64  04 04 04 04 04 05 06 07 08 09 0a 0b  buflen: 12
65  05 05 05 05 05 05 06 07 08 09 0a 0b  buflen: 12
66  06 06 06 06 06 06 06 07 08 09 0a 0b  buflen: 12
67  .. .. 07 07 07 07 07 07 08 09 0a 0b  buflen: 10
68  .. .. .. .. 08 08 08 08 08 09 0a 0b  buflen: 8
69  .. .. .. .. .. .. 09 09 09 09 0a 0b  buflen: 6
6a  .. .. .. .. .. .. .. .. 0a 0a 0a 0b  buflen: 4
6b  .. .. .. .. .. .. .. .. .. .. 0b 0b  buflen: 2

114 matrix cells allocated
distance: 11
  a  ->   A  changes: 1
  b  ->   B  changes: 2
  c  ->   C  changes: 3
  d  ->   D  changes: 4
  e  ->   E  changes: 5
  f  ->   F  changes: 6
  g  ->   G  changes: 7
  h  ->   H  changes: 8
  i  ->   I  changes: 9
  j  ->   J  changes: 10
  k  ->   K  changes: 11
```

2021-03-18 18:34 UTC, trufae commented
Please the CI and i'll merge! i have some plans to improve the diffing and signature matching code and having this new api was in the path.

```

337
      | 
338
udiff.c:349:2: error: ‘r_return_if_fail’ undeclared (first use in this function)
339
  349 |  r_return_if_fail (a && b, false);
340
      |  ^~~~~~~~~~~~~~~~
341
udiff.c:349:2: note: each undeclared identifier is reported only once for each function it appears in
```

2021-03-18 18:45 UTC, swoops commented
The thought just occurred to me that I might be able to abstract this enough to make it work on any totally ordered set. The alg really only cares about adjusting length of the two sets and getting comparisons between elements. I think I could abstract that with function pointers.

Then it could be used to find the minim number of changes between two ESIL expressions. So `radiff2` could do a function by function comparison in ESIL. Potentially you could run it on functions themselves. So whats is the minimum number of functions you should add / delete / substitute to get from one binary to another. 

Should I try this?

2021-03-18 19:33 UTC, trufae commented
udiff.c.obj : error LNK2019: unresolved external symbol reallocarray referenced in function lev_parse_matrix

2021-03-18 19:34 UTC, trufae commented
udiff.c: In function ‘lev_parse_matrix’:
521
udiff.c:96:14: error: implicit declaration of function ‘reallocarray’; did you mean ‘realloc’? [-Werror=implicit-function-declaration]
522
   if ((arr = reallocarray (arr, sizeof (RLevOp), sz)) == NULL) { \
523
              ^
524
udiff.c:132:5: note: in expansion of macro ‘lev_set_next_op’
525
     lev_set_next_op (changes, insert, size, LEVNOP);
526
     ^~~~~~~~~~~~~~~
527
udiff.c:96:12: error: assignment makes pointer from integer without a cast [-Werror=int-conversion]
528
   if ((arr = reallocarray (arr, sizeof (RLevOp), sz)) == NULL) { \
529
            ^
530
udiff.c:132:5: note: in expansion of macro ‘lev_set_next_op’
531
     lev_set_next_op (changes, insert, size, LEVNOP);
532
     ^~~~~~~~~~~~~~~
533
udiff.c:96:12: error: assignment makes pointer from integer without a cast [-Werror=int-con

2021-03-18 21:47 UTC, swoops commented
I am not sure what to do about that error? I thought `reallocarray` was from same library as `malloc`. Is it less portable? Should I create our own `reallocarray` function using `realloc` if `reallocarray` is not defined?

2021-03-19 09:02 UTC, trufae commented
realloc array is not portable. actually i have never heard of it, i guess you can use just `realloc`. also dont assign the result of realloc to the same variable you are resizing, because this way you cant catch when there's an actual error and ends up leaking memory because you loose the pointer.

2021-03-19 09:05 UTC, trufae commented on libr/util/udiff.c
> +
you can realloc the array in here once. as long as every path below needs it, so you can avoid the use of the macro

2021-03-19 09:06 UTC, trufae commented on libr/util/udiff.c
> +	r_return_val_if_fail (len >= 2 && chgs && !*chgs, -1);
check for matrix too

2021-03-19 09:06 UTC, trufae commented on libr/util/udiff.c
> +	ut32 i;
better use size_t than ut32 when indexing in pointers

2021-03-19 09:07 UTC, trufae commented on libr/util/udiff.c
> +		if (matrix[i].changes) {
this changes pointer is never touched, freeing NULL is legit, so i would simplify that by removing the conditional blocks around

2021-03-19 09:07 UTC, trufae commented on libr/util/udiff.c
> +
empty line

2021-03-19 09:07 UTC, trufae requested changes
.

2021-03-19 16:21 UTC, swoops commented
I only found `reallocarray` when looking at man page for `realloc`. It's equivalent to `realloc(ptr, nmemb * size)` but guards against overflowing `size` in the multiplication. 

The `size` we use can't be much larger then the length of a row. So I suspect we would run out of memory before a `row * sizeof (RLevOp) * 2` will overflow. I threw a guard in there anyways.

Let me know if you have something better, or if I am being to paranoid.

2021-03-19 16:26 UTC, swoops commented
I messed up something, give me a minute.

2021-03-19 16:39 UTC, trufae commented
I wrote a multiply overflow macro you can use if its something to worry.

2021-03-19 16:42 UTC, merged