Implemented r_io_submap_set_from and r_io_submap_set_to functions
radareorg/radare2 pull request #18504
Opened 2021-03-25 17:44 UTC by redin0s

- [x]  Closing issues: #18476 
- [x] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [radare2book](https://github.com/radareorg/radare2book)

**Description**

Implemented the functions required by the issue.
I'm not sure if I did it correctly, is `r_return_val_if_fail` needed in this situation or not?

2021-03-26 20:14 UTC, condret requested changes
please use r_return_val_if_fail for null-pouinter-checks and add missing functionality.

Also start commit message with uppercase letter and use ```sys/indent.sh -i libr/io/submap.c```

2021-03-26 20:14 UTC, condret commented on libr/io/io_submap.c
> +R_API bool r_io_submap_set_to(RIOSubMap *sm, const ut64 to) {
this function shall adjust ```sm->itv.size``` so that ```r_io_submap_to``` returns the given ```to```

2021-03-26 20:14 UTC, condret commented on libr/io/io_submap.c
> +R_API bool r_io_submap_set_from(RIOSubMap *sm, const ut64 from) {
this function shall adjust ```sm->itv.addr```, so that ```r_io_submap_from``` returns the given ```from```, without affecting ```r_io_submap_to```

2021-03-26 20:16 UTC, condret commented on libr/io/io_submap.c
> +R_API bool r_io_submap_set_from(RIOSubMap *sm, const ut64 from) {
Add function signatures to ```libr/include/r_io.h```

2021-03-29 12:33 UTC, trufae commented
ping  @redin0s

2021-04-01 19:55 UTC, trufae commented
reping

2021-04-09 21:17 UTC, closed without merging

2021-04-09 21:25 UTC, condret commented
I closed this pr, as I see no activity here for 2 weeks. The issue was created to give new devs a chance to do an easy contribution. Keeping it open could look like as if someone is working on this, even if this is not the case.
@redin0s Feel free to reopen the pr, once you have time/energy/motivation to continue working on this.