Update arm.sdb.txt file with opcodes
radareorg/radare2 pull request #18878
Opened 2021-07-01 15:13 UTC by alex-bender

**Checklist**
- [x] Mark this if you consider it ready to merge

**Description**

Add some opcodes generated from https://developer.arm.com/documentation/ddi0596/2021-03/Base-Instructions?lang=en
with help of
```
let doc = $('[role=document]');
var x = document.createElement("TEXTAREA");
document.body.appendChild(x);

for (var i=1; i<doc.childElementCount; i++) {
  var el = doc.children[i];
  if (el.nodeName == 'DIV') {
    x.value += ('\n' + doc.children[i].textContent);
  }
}
```
and 
```
data = open('./arm.txt').readlines()
def filter(line):
    coma = line.find(',')
    dots = line.find(':')
    part = line[:dots]
    if ',' in part and coma < dots:

        opcodes = part.split(', ')
        descr = line[dots+1:].strip()
        for opcode in opcodes:
            print(f'{opcode.lower()}={descr}'.strip())
    else:
        opcode = line.split(':')[0]
        descr = line[dots+1:].strip()
    print(f'{opcode.lower()}={descr}')

res = list(map(filter, data))
```

2021-07-01 18:19 UTC, trufae commented
Maybe worth having this script somewhere.. maybe in extras?

2021-07-02 09:50 UTC, radare commented on libr/asm/d/arm.sdb.txt
> +casalb=Compare and Swap byte in memory
can you uncapitalize all the words in those strings? lowercase is fine

2021-07-02 09:51 UTC, radare commented on libr/asm/d/arm.sdb.txt
> +add=Add
not very descriptive. old text was clearer in this case
![Screenshot 2021-07-02 at 11 50 46](https://user-images.githubusercontent.com/917142/124256607-ca5b7480-db2b-11eb-8e76-1c8f5d84f47d.png)

2021-07-02 09:52 UTC, radare requested changes
did you checked if any of the old entries is not available in the new autogenerated format? this file should contain arm, thumb and arm64 instruction descriptions.

2021-07-05 12:58 UTC, radare commented
Ping

2021-07-05 13:38 UTC, alex-bender commented
> did you checked if any of the old entries
Looks like I've forgot to do that.
Will check it today and add the script for that check as well

2021-07-15 20:19 UTC, alex-bender commented
> did you checked if any of the old entries is not available in the new autogenerated format?

I've added only opcodes which was not in file already

2021-07-18 16:43 UTC, merged