Use r_sys_whoami as the author name for r_vc_commit ##projects
radareorg/radare2 pull request #18915
Opened 2021-07-18 19:19 UTC by RHL120

**Checklist**

- [ ] Closing issues: #issue
- [X] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [radare2book](https://github.com/radareorg/radare2book)

**Description**
r_vc_commit now checks if author is NULL in case it is it sets author to the value of prj.vc.author. prj.vc.author is by default set to the return value of r_sys_whoami().

2021-07-18 22:15 UTC, trufae commented on libr/core/rvc.c
> +	author = author? author : r_config_get (core->config, "prj.vc.author");
Instead of calling config and core here just do this in the caller. So rvc stays independent

2021-07-18 22:16 UTC, trufae commented on libr/core/rvc.c
>  	return message ? r_sys_cmdf ("git -C %s commit -m %s", path, message) :
Use quotes around “” and escape the strings passed

2021-07-18 22:16 UTC, trufae requested changes

2021-07-18 22:16 UTC, trufae commented on libr/core/rvc.c
> -		r_vc_commit (rp, message, author, files);
Get vc.user here instead

2021-07-18 23:30 UTC, trufae requested changes

2021-07-18 23:30 UTC, trufae commented on libr/core/rvc.c
> +	return r_sys_cmdf ("git init \"%s\"", r_str_escape (path));
Leaks

2021-07-18 23:30 UTC, trufae commented on libr/core/rvc.c
> +	return !r_sys_cmdf ("git -C \"%s\" checkout \"%s\"", r_str_escape (path),
Leaks too

2021-07-18 23:30 UTC, trufae commented on libr/core/cconfig.c
> +		SETBPREF ("prj.vc.user", r_sys_whoami(),
```suggestion
		SETBPREF ("prj.vc.user", r_sys_whoami (),
```

2021-07-20 00:47 UTC, trufae commented
What about reusing cfg.user?

2021-07-20 05:57 UTC, RHL120 commented
> What about reusing cfg.user?

Well, I don't know one one hand it is good because it doesn't add a new (possibly pointless) variable but on the other hand it might discourage the user from configuring it because this is a variable used not just by rvc but by r2 in it's entirety so to the user changing it might cause some unintended consequences. I already committed tell me if you want me to revert.

2021-07-20 23:01 UTC, trufae commented
Yeah i have divided opinion here but i would probably pick cfg.user because we want to be in sync with r2.. but for me cfg.user contains username and vc.author should be name + mail

2021-07-21 08:54 UTC, RHL120 commented
> Yeah i have divided opinion here but i would probably pick cfg.user because we want to be in sync with r2.. but for me cfg.user contains username and vc.author should be name + mail

Just to clarify are you saying you want there to be a vc.author.name & a vc.author.mail? rvc has no use for the users email and adding emails to commit would only complicate the code because either we force the user to set an email or we end up having to deal with empty values which is doable but not pleasent.

2021-07-21 08:58 UTC, RHL120 commented
> Yeah i have divided opinion here but i would probably pick cfg.user because we want to be in sync with r2.. but for me cfg.user contains username and vc.author should be name + mail

Maybe we should just force the user to use their username so just r_sys_whoami without setting up any vars this would remove the need for core->config and thus make the code faster but on the other hand it will disable the customization abilities which in my opinion are already dead if we were to use cfg.user (that's because of possible side-effects)

2021-07-21 10:04 UTC, merged