Fix x86.nz invalid assembly #18876
radareorg/radare2 pull request #18942
Opened 2021-07-26 21:18 UTC by as0ler

2021-07-26 21:20 UTC, trufae commented on libr/asm/p/asm_x86_nz.c
>  	} else {
Thats a compile time check. You should check the immediate value instead of its size

2021-07-26 21:21 UTC, trufae commented on libr/asm/p/asm_x86_nz.c
> +			eprintf ("Invalid Immediate value\n");
```suggestion
			eprintf ("Immediate value is out of range.\n");
```

2021-07-26 23:33 UTC, trufae reviewed
Looks good after this change! Can you add a test?

2021-07-26 23:33 UTC, trufae commented on libr/asm/p/asm_x86_nz.c
> +		if (a->bits == 32 && (op->operands[0].immediate >> 32) > 0) {
I think is better to drop the >0. Negative values could be a problem if imm is signed i think

```suggestion
		if (a->bits == 32 && (op->operands[0].immediate >> 32)) {
```

2021-07-27 15:06 UTC, radare commented
Also this bound check affects many other instructions. can you write some tests for them too?

2021-07-27 15:08 UTC, radare commented
Remove the submodule that is breaking the build please:

```
0 / 2 files viewed
Review changes 
 1  libr/asm/arch/arm/v35arm64/arch-arm64 
Viewed

 Submodule arch-arm64 added at 583791
 ```

2021-07-29 18:06 UTC, trufae commented on libr/asm/p/asm_x86_nz.c
> +		if (a->bits == 32 && (op->operands[0].immediate >> 32) > 0) {
^

2021-07-29 18:06 UTC, trufae requested changes
.

2021-07-30 08:34 UTC, trufae commented on libr/asm/p/asm_x86_nz.c
> +		if(immediate_out_of_range(a->bits, op->operands[1].immediate)) {
```suggestion
		if (immediate_out_of_range (a->bits, op->operands[1].immediate)) {
```

2021-07-30 08:34 UTC, trufae commented on libr/asm/p/asm_x86_nz.c
> +static int immediate_out_of_range(int bits, ut64 immediate) {
```suggestion
static bool immediate_out_of_range(int bits, ut64 immediate) {
```

2021-07-30 08:34 UTC, trufae commented on libr/asm/p/asm_x86_nz.c
> +	return (bits == 32 && (immediate >> 32) > 0);
```suggestion
	return bits == 32 && (immediate >> 32); 
```

2021-07-30 08:35 UTC, trufae commented on libr/asm/p/asm_x86_nz.c
> +		if(immediate_out_of_range(a->bits, op->operands[0].immediate)) {
```suggestion
		if (immediate_out_of_range (a->bits, op->operands[0].immediate)) {
```

2021-07-30 08:35 UTC, trufae commented on libr/asm/p/asm_x86_nz.c
> +		if(op->operands[0].immediate > 255) {
```suggestion
		if (op->operands[0].immediate > 255) {
```

2021-07-30 08:35 UTC, trufae requested changes
see code suggestions and lgtm if grin

2021-07-30 08:51 UTC, trufae commented
the new output is correct. use r2r -i to update the test .

![Screenshot 2021-07-30 at 10 50 46](https://user-images.githubusercontent.com/6431515/127627838-69a8176c-96d3-4344-9bea-07d551adaadd.png)

2021-07-30 09:26 UTC, merged