Support .a files in rasign2 ##signatures
radareorg/radare2 pull request #19085
Opened 2021-09-15 07:07 UTC by swoops

**Checklist**

- [ ] Closing issues: #issue
- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [radare2book](https://github.com/radareorg/radare2book)

**Description**
This is a work in progress. I need to update the man page and add tests.

This is a hack to add initial support for .a (ar archive files of .o object files) to rasign2 without having openmany support in core. An even bigger hack is using a new `RCore` for each object file. But the following basic algorithm in pseudocode did not work.

```
core = r_core_new ()
for (objectfile in archive) {
    r_core_file_open (core, objectfile, 0, 0)
    r_core_bin_load (core, NULL, UT64_MAX)
   file_functions (core)
   create_signatures (core)
   r_core_file_close_all_but (core) # closes the objectfile?
}
output_signatures (core)   
```

So let me know if there is a better way. This is a stop gap until `r_core_file_open_many` is fixed anyways.

2021-09-15 09:05 UTC, trufae commented
That failing test should be fixed in master just in case you rebase :}

2021-09-15 22:43 UTC, swoops commented
About to make the man page update. Before I do, is usage ok? As it is, `rasign2 -o sigfile.sdb -A libc-dev.a` is how it works. The `-A` tells rasign2 to treat `libc-dev.a` as an ar archive of `.o` files and only make signatures for files ending in `.o`.

This means `rasign2 arall://somefile.a` or `rasign2 ar://somefile.a//someotherfile.exe` will just open the proved file with `io` and go about trying to analyze and make signatures from it.

2021-09-15 23:21 UTC, swoops commented
Man page updated. I happy to make any requested changes. Otherwise, I think this is ready to merge.

2021-09-16 08:05 UTC, trufae commented
Looks good so far!

2021-09-16 08:46 UTC, trufae commented on libr/main/rasign2.c
> +	struct rasignconf conf;
```suggestion
	struct rasignconf conf = {0};
```

2021-09-16 08:46 UTC, trufae commented on libr/main/rasign2.c
> +		} else if (conf.collision && conf.rad) {
dont else after return

2021-09-16 08:46 UTC, trufae commented on libr/main/rasign2.c
> +		} else {
same here

2021-09-16 08:47 UTC, trufae commented on libr/main/rasign2.c
> +
remove all those empty lines

2021-09-16 08:47 UTC, trufae requested changes
.

2021-09-16 16:34 UTC, swoops commented
I think I took care of everything requested. Let me know if you find anything else.

2021-09-16 18:27 UTC, merged