Cleanup public API for ##search
radareorg/radare2 pull request #19477
Opened 2021-12-07 22:22 UTC by swoops

**Checklist**

- [ ] Closing issues: #issue
- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [radare2book](https://github.com/radareorg/radare2book)

**Description**

Trying to clean up the r_search API a bit.

A couple functions in r_earch.h were not used or were duplicates.

I moved the update functions into their own .h file to hide them from public use. They should only be used internally. I have not made this type of change in r2 before, so I probably am not doing it just right.

2021-12-08 00:19 UTC, trufae commented on libr/search/aes_find.c
> +int search_aes_update(RSearch *s, ut64 from, const ut8 *buf, int len) {
use R_IPI for internal apis (functions that are meant to be used only inside the module, static for the file-specific and R_API for the public ones. Not sure if this is documented in DEVELOPERS.md but it should be

2021-12-08 00:21 UTC, trufae requested changes

2021-12-08 00:21 UTC, trufae commented on libr/include/r_search.h
> -R_API int r_search_mybinparse_update(RSearch *s, ut64 from, const ut8 *buf, int len);
maybe just use R_IPI in here :? i think its fine to make them internal. so the change lgtm.

2021-12-08 21:39 UTC, swoops commented
I broke something bad....

2021-12-09 00:21 UTC, trufae commented on libr/include/r_search.h
> -	R_SEARCH_PATTERN,
that should route the call to `r_search_pattern`, the problem is that this 'mode' doesnt follows the same callback model. so it cant reuse the searchupdate loop. will be good to get this fixed too

2021-12-12 10:46 UTC, merged