fixed x86-16bit seg:off disassembly print for seg=0
radareorg/radare2 pull request #19608
Opened 2022-01-20 23:21 UTC by lasek0

**Checklist**

- [ ] Closing issues: #issue
- [x] Mark this if you consider it ready to merge
- [x] I've added tests (optional)
- [ ] I wrote some lines in the [radare2book](https://github.com/radareorg/radare2book)

**Description**

fixed x86-16bit seg:off disassembly print for seg=0. now analysed function name can be correctly printet in disassembly.
tests done and requested in https://github.com/radareorg/radare2/pull/19607 PR

no issue was opened for that bug.

2022-01-21 09:14 UTC, trufae requested changes
lgtm! can you refactor this while condition and add another test for this case? looks good so far! thank you!

2022-01-21 09:14 UTC, trufae commented on libr/core/disasm.c
> +				while ((*nptr && !IS_SEPARATOR (*nptr) && *nptr != 0x1b) || (x86 && bits == 16 && colon && *nptr == ':')) {
as long as the conditional is starting to be hrad to read, better to decompose it into another form. try something like:

```c
while (*nptr) {
   // condition to break 
   // the new condition to break
}
```

2022-01-21 14:09 UTC, lasek0 commented
Tests for that cases are added in that PR 
https://github.com/radareorg/radare2/pull/19607 In general I added more test cases for previous x86-16 PRs, then I found spare time to try fix one of failing test. I agree that this while condition is hard to read. I will refactor this when I found spare free times.

2022-01-21 14:44 UTC, trufae commented
i can merge and improve the loop later if it's ok for you. the code looks good

2022-01-21 22:10 UTC, merged

2022-01-22 11:46 UTC, Lazula commented
wrong PR reference, the one i wanted was merged by hand