Significantly reduce memory leaks in anal tests
radareorg/radare2 pull request #19759
Opened 2022-02-27 19:45 UTC by Lazula

**Description**

Fix lots of memory leaks for anal tests. Not totally clean yet.

2022-02-27 20:02 UTC, trufae requested changes
you cant call rbin apis from shlr/

2022-02-27 20:05 UTC, Lazula commented on libr/anal/class.c
> +		char *flagname = flagname_method (class_name, cur);
what do you mean?

2022-02-27 20:06 UTC, Lazula commented on libr/asm/p/asm_dalvik.c
> +	R_FREE (flag_str);
i used R_FREE for the autocast from const, will change

2022-02-27 20:09 UTC, Lazula commented on libr/anal/class.c
> +		char *flagname = flagname_method (class_name, cur);
unset_flag does have null checking, and its done like this elsewhere

2022-02-27 20:57 UTC, merged

2022-03-01 07:16 UTC, swoops commented
Nice work! You caught a few leaks I had been hunting.