Add support for Kalray VLIW archictecture aka KVX
radareorg/radare2 pull request #19764
Opened 2022-02-28 17:19 UTC by jmaselbas

- [x] Mark this if you consider it ready to merge
- [x] I've added tests (optional) [test-bin#71](https://github.com/radareorg/radare2-testbins/pull/71)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

Add support for Kalray VLIW archictecture aka KVX

KVX is VLIW architecture, kind of like a DSP, it can execute more than
one "instruction" per cycle. Each cycle a bundle of instruction is
executed which is comprised of up to 6 instructions. The general rules
for bundle are: only one BCU instruction (which comes first); only one
LSU instruction; and up to 5 ALU instructions (depending on the type).

In assembly the end of a bundle is marked by a `;;` in an empty line, here
in r2 (to make things more compact and readable) the end of bundle is
appended after the last instruction, but beware that this is not valid
kvx assembly.

2022-02-28 17:38 UTC, jmaselbas commented
I have have some questions on the build system, I don't know how to properly test the meson build (even less for the windows builds) and I might I've missed changes from "merging" the asm to anal pluging

2022-03-01 15:12 UTC, trufae requested changes
Looks good to me! is there anything that doesnt works for you?

2022-03-01 15:12 UTC, trufae commented on libr/anal/p/anal_kvx.c
> +	if (insn == NULL) {
```suggestion
	if (!insn) {
```

2022-03-01 15:12 UTC, trufae commented on libr/anal/p/anal_kvx.c
> +	insn = kvx_next_insn (&bundle, addr, b, len);
```suggestion
	insn_t *insn = kvx_next_insn (&bundle, addr, b, len);
```

2022-03-01 15:12 UTC, trufae commented on libr/anal/p/anal_kvx.c
> +	insn_t *insn;
```suggestion
```

2022-03-02 10:22 UTC, trufae commented
../libr/anal/p/anal_kvx.c(227): error C2059: syntax error: '}'

2022-03-02 10:30 UTC, trufae requested changes

2022-03-02 10:30 UTC, trufae commented on libr/anal/arch/kvx/kvx-dis.c
> +		if (!kvx_has_parallel_bit (word))
missing braces {}

2022-03-02 10:30 UTC, trufae commented on libr/anal/arch/kvx/kvx-dis.c
> +	issue = KVX_MAX_BUNDLE_ISSUE;
```suggestion
	int issue = KVX_MAX_BUNDLE_ISSUE;
```
define and assign in the same line

2022-03-02 10:30 UTC, jmaselbas commented
```../libr/anal/p/anal_kvx.c(227): error C2059: syntax error: '}'```
That might be a compiler bug, looks like https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53119 
the struct is initialized with `= { };` even tho this isn't needed because it's declared as static; I will remove the `= { };`

2022-03-02 10:41 UTC, jmaselbas commented on libr/anal/p/anal_kvx.c
> +	static bundle_t bundle = { };
yes it must be static... that's a hack. this in order to return each instruction of a bundle individually...
That's ugly but I've not found a better way of doing this.
OK will make the change to `static R_TH_LOCAL`

2022-03-02 10:42 UTC, jmaselbas commented on libr/anal/arch/kvx/kvx-dis.c
> +/* radare - LGPL - Copyright 2022 - jmaselbas */
I didnt get the question.

2022-03-02 10:54 UTC, trufae commented on libr/anal/arch/kvx/kvx-dis.c
> +/* radare - LGPL - Copyright 2022 - jmaselbas */
the plugin description specifies "GPL" as the license for this plugin, so the header should reflect that, if its coming from binutils it shold be GPL, but if its a clean/rework reimplementaion for r2 you can pick any other license. just trying to clarify that before the debian maintainers complain :D

2022-03-02 12:06 UTC, trufae commented
Looks good now!

2022-03-02 12:22 UTC, jmaselbas commented on libr/anal/arch/kvx/kvx-dis.c
> +/* radare - LGPL - Copyright 2022 - jmaselbas */
it's a reimplementation for r2. Only the `disassemble_bundle` function is a rework of an existing version from binutils.

2022-03-02 12:28 UTC, jmaselbas commented
OK I happy with this version being merged

2022-03-02 12:56 UTC, merged