Provide a macro to turn off EPRINT for running tests
radareorg/radare2 pull request #19770
Opened 2022-03-01 02:16 UTC by Lazula

EPRINT macros are useful for debugging, but they can interfere with program output while running tests. This patch adds a macro that can be easily switched on and off to suppress the output from these macros if desired.

2022-03-01 14:59 UTC, trufae commented on libr/include/r_types.h
> +#define USE_DEBUG_VAR_PRINTS 1
uhmf the user cant override this value with an env var or configure option.. so it seems like that should be wrapped inside an #ifdef

2022-03-03 21:57 UTC, Lazula commented
freebsd ssh dying again...

2022-03-03 23:30 UTC, trufae commented
Oh noes i maybe didnt explained well what i was refering was a way to redefine that value from commandline or adding a cflags. Sysgetenv is overkill here

2022-03-04 17:59 UTC, Lazula commented
hmm, idk exactly how to do that. runtime checking is very useful though as it lets you build with the debug prints but turn it off if you want, plus r2r can always disable which imo is nice and convenient instead of needing to rebuild with it disabled to run tests

2022-03-04 18:12 UTC, trufae commented
Is what you had before but adding an #ifndef/#endif ... before defining the variable that shows/hides the debug prints

2022-03-29 16:28 UTC, Lazula commented
Has both compile-time and run-time options to disable now

2022-03-30 08:33 UTC, trufae commented on binr/r2r/r2r.c
> +	r_sys_setenv ("R2_SUPPRESS_VAR_EPRINT", "1");
```suggestion
	r_sys_setenv ("R2_DEBUG_EPRINT", "1");
```

2022-03-30 08:35 UTC, trufae commented on libr/include/r_types.h
> +#ifndef NO_EPRINT_MACROS
Else?

2022-03-31 15:26 UTC, Lazula commented
I think `NO_EPRINT_MACROS` (compile flag) and `R2_NO_EPRINT_MACROS` (env) are good names for this.

2022-04-01 10:27 UTC, trufae commented
i would keep the same name for define and env var.

2022-04-01 10:29 UTC, trufae requested changes

2022-04-01 10:29 UTC, trufae commented on libr/include/r_types.h
> +#ifdef NO_EPRINT_MACROS
```suggestion
#ifndef R2_DEBUG_EPRINT
#define R2_DEBUG_EPRINT 0
#endif
#if !R2_DEBUG_EPRINT
```

2022-04-01 10:29 UTC, trufae commented on binr/r2r/r2r.c
> +	r_sys_setenv ("R2_NO_EPRINT_MACROS", "1");
```suggestion
	r_sys_setenv ("R2_DEBUG_EPRINT", "0");
```

2022-04-01 10:30 UTC, trufae commented
lgtm after applying my suggestion changes

2022-04-01 18:51 UTC, merged