Add an error return to r_core_project_cat ##projects
radareorg/radare2 pull request #19881
Opened 2022-03-27 11:07 UTC by RHL120

- [X] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

2022-03-27 22:43 UTC, trufae commented on libr/core/project.c
>  R_API int r_core_project_cat(RCore *core, const char *name) {
I think it should return bool. The command handler who calls this function is the one that must change the return code

2022-04-08 19:17 UTC, trufae commented
Please rebase and try again when https://github.com/radareorg/radare2/pull/19897 gets merged

2022-04-08 21:12 UTC, trufae commented
I would like to move core/rvc.c into util/vc.c and rename include/rvc.h to include/r_util/vc.h

the only blocker for this seems to be only the dependency on r_hash. So i propose making this a function pointer that RCore can replace to substitute the default algorithm. Ideally there should be always the same checksum algorithm used everywhere.. so i'm not fully convinced about this solution. what do you think?

2022-04-08 21:14 UTC, trufae requested changes
pls merge those changes and rebase

2022-04-08 21:14 UTC, trufae commented on libr/core/project.c
> +			core->num->value = 0;
```suggestion
			r_core_return_code (core, R_CMD_RC_SUCCESS);
```

2022-04-08 21:14 UTC, trufae commented on libr/core/project.c
> +	core->num->value = 1;
```suggestion
				r_core_return_code (core, R_CMD_RC_FAILURE);
```

2022-04-17 14:27 UTC, Lazula commented
The test `Save PE project with maddr` will be fixed by #19965

2022-04-17 16:58 UTC, merged