Add help messages for ms mp mL mo commands
radareorg/radare2 pull request #20161
Opened 2022-05-24 21:32 UTC by alex-bender

https://github.com/radareorg/radare2/issues/19968
The `mk?` left unfixed. Looks like it is absent now. 

- [x] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

2022-05-24 23:06 UTC, trufae commented on libr/core/cmd_mount.c
> +	"Usage:", "md /", "list directory contents for path",
```suggestion
	"Usage:", "md /", "list files and directory on the virtual r2's fs",
	"md", " /", "list directory on the root directory",
	"md", "", "list files and directories in current directory",
```

2022-05-24 23:06 UTC, trufae commented on libr/core/cmd_mount.c
> +		}
Else instead of break

2022-05-24 23:09 UTC, trufae requested changes
@Lazula did an api to show the help grepping with a word. Maybe we can use that here if the subcommand helps dont provide much extra subcommands

2022-05-24 23:49 UTC, Lazula commented
I recommend that you edit `help_msg_m` instead of creating new messages. Then you can use `r_core_cmd_help_match_spec(core, help_msg_m, "m", <*input, input[1], etc.>, true);`, but you will need to do this before advancing the input pointer in each command.

If you want help for one specific command, this is a better way to do it. Separate help messages ought to only be used when there are subcommands to list. Doing it this way also prevents clutter in recursive help.

2022-05-26 23:37 UTC, trufae approved these changes

2022-05-26 23:37 UTC, trufae commented on libr/core/cmd_mount.c
> +			r_core_cmd_help_match_spec(core, help_msg_m, "mL", 0, true);
```suggestion
			r_core_cmd_help_match_spec (core, help_msg_m, "mL", 0, true);
```

2022-05-26 23:37 UTC, trufae commented on libr/core/cmd_mount.c
> +			r_core_cmd_help_match_spec(core, help_msg_m, "md", 0, true);
```suggestion
			r_core_cmd_help_match_spec (core, help_msg_m, "md", 0, true);
```

2022-05-26 23:37 UTC, trufae commented on libr/core/cmd_mount.c
> +			r_core_cmd_help_match_spec(core, help_msg_m, "mp", 0, true);
```suggestion
			r_core_cmd_help_match_spec (core, help_msg_m, "mp", 0, true);
```

2022-05-26 23:37 UTC, trufae commented on libr/core/cmd_mount.c
> +			r_core_cmd_help_match_spec(core, help_msg_m, "mo", 0, true);
```suggestion
			r_core_cmd_help_match_spec (core, help_msg_m, "mo", 0, true);
```

2022-05-26 23:37 UTC, trufae commented on libr/core/cmd_mount.c
> +			r_core_cmd_help_match_spec(core, help_msg_m, "ms", 0, true);
```suggestion
			r_core_cmd_help_match_spec (core, help_msg_m, "ms", 0, true);
```

2022-05-26 23:38 UTC, merged