Fix #20206 - pthread_create: Resource temporarily unavailable
radareorg/radare2 pull request #20213
Opened 2022-06-02 20:48 UTC by pipothebit

Fix error that appears when running a long session with esil.
https://github.com/radareorg/radare2/issues/20206

- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

2022-06-02 23:23 UTC, trufae requested changes
Can you confirm the suggested patch works as expected for you too?

2022-06-02 23:23 UTC, trufae commented on libr/lang/p/pipe.c
> +	waitpid (child, NULL, WUNTRACED);
```suggestion
	waitpid (child, NULL, WNOHANG | WUNTRACED);
```

2022-06-02 23:25 UTC, trufae commented
related doc https://stackoverflow.com/questions/33508997/waitpid-wnohang-wuntraced-how-do-i-use-these

2022-06-03 11:06 UTC, pipothebit commented
I've just tested your change and it doesn't work, zombie processes still remain there on every pipe call until r2 closes.

According to the documentation the options parameter of the ```waitpid``` function can have a combination of 3 possible values: ```WCONTINUED```, ```WNOHANG``` and ```WUNTRACED```. I've been doing some tests and when ```WNOHANG``` is used as an option, if ```waitpid``` returns 0, that process goes zombie. If using ```WNOHANG``` ```waitpid``` returns 0, the state of the child process has not changed. I don't know what to do in this case, I'm just a rookie in c programming,

2022-06-03 12:00 UTC, merged