Replace some instances of eprintf with R_LOG_
radareorg/radare2 pull request #20367
Opened 2022-06-27 12:52 UTC by terorie

- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

2022-06-27 12:55 UTC, terorie reviewed
some bugs

2022-06-27 12:55 UTC, terorie commented on libr/anal/fcn.c
> +		D R_LOG_WARN ("Warning: r_anal_function_add_bb failed in fcn 0x%08"PFMT64x" at 0x%08"PFMT64x"", fcn->addr, addr);
```suggestion
		D R_LOG_WARN ("Warning: r_anal_function_add_bb failed in fcn 0x%08"PFMT64x" at 0x%08"PFMT64x, fcn->addr, addr);
```

2022-06-27 12:55 UTC, terorie commented on libr/anal/fcn.c
> +			R_LOG_WARN ("Warning: invalid bb jump/fail pair at 0x%08"PFMT64x" (fcn 0x%08"PFMT64x"", bb->addr, fcn->addr);
```suggestion
			R_LOG_WARN ("Warning: invalid bb jump/fail pair at 0x%08"PFMT64x" (fcn 0x%08"PFMT64x, bb->addr, fcn->addr);
```

2022-06-27 13:03 UTC, trufae requested changes
Cmdline tools probably are fine to report errors via eprintf (see failing tests)

2022-06-27 13:03 UTC, terorie reviewed
some bugs

2022-06-27 13:03 UTC, terorie commented on libr/core/blaze.c
> +		// R_LOG_WARN ("Warning: Invalid memory address at 0x%08"PFMT64x"", addr);
```suggestion
		// R_LOG_WARN ("Warning: Invalid memory address at 0x%08"PFMT64x, addr);
```

2022-06-27 13:03 UTC, terorie commented on libr/core/canal.c
> +			R_LOG_WARN ("Warning: unsorted flag list 0x%"PFMT64x" 0x%"PFMT64x"", a0, a1);
```suggestion
			R_LOG_WARN ("Warning: unsorted flag list 0x%"PFMT64x" 0x%"PFMT64x, a0, a1);
```

2022-06-27 13:03 UTC, terorie commented on libr/core/canal.c
> +			R_LOG_WARN ("Warning: invalid flag range from 0x%08"PFMT64x" to 0x%08"PFMT64x"", a0, a1);
```suggestion
			R_LOG_WARN ("Warning: invalid flag range from 0x%08"PFMT64x" to 0x%08"PFMT64x, a0, a1);
```

2022-06-27 13:03 UTC, terorie commented on libr/debug/p/native/w32.c
> +	R_LOG_ERROR ("ErrorSelector = %08x DataSelector = %08x", ctx->FltSave.ErrorSelector, ctx->FltSave.DataSelector);
revert

2022-06-27 13:03 UTC, terorie commented on libr/debug/p/native/w32.c
> +	R_LOG_ERROR ("ErrorSelector = %08x DataSelector = %08x", (ut32)ctx->FloatSave.ErrorSelector, (ut32) ctx->FloatSave.DataSelector);
revert

2022-06-27 13:03 UTC, terorie commented on libr/debug/p/native/windows/windows_debug.c
> +	R_LOG_ERROR ("ErrorSelector = %08x DataSelector = %08x", ctx->FltSave.ErrorSelector, ctx->FltSave.DataSelector);
revert

2022-06-27 13:03 UTC, terorie commented on libr/debug/p/native/windows/windows_message.c
> +		R_LOG_ERROR ("Error trying to get information from 0x%08"PFMT64x"", (ut64)hwnd);
```suggestion
		R_LOG_ERROR ("Error trying to get information from 0x%08"PFMT64x, (ut64)hwnd);
```

2022-06-27 13:08 UTC, terorie commented on sys/lint.sh
> +(git grep 'R_LOG_' | grep '\\n' | grep -v sys/) && exit 1
```suggestion
(git grep 'R_LOG_' | grep '\\n' | grep -v sys/) ## && exit 1
```

2022-06-27 13:30 UTC, trufae commented on libr/util/str.c
> +				R_LOG_ERROR ("Error: Non-hexadecimal chars in input.");
Same

2022-06-27 13:31 UTC, trufae commented on sys/lint.sh
> +(git grep 'R_LOG_' | grep '\\n' | grep -v sys/) ## && exit 1
```suggestion
(git grep 'R_LOG_' | grep '\\n' | grep -v sys/) && exit 1
```

2022-06-27 13:32 UTC, terorie commented on libr/util/str.c
> +				R_LOG_ERROR ("Error: Non-hexadecimal chars in input.");
fixed all instances

2022-06-27 13:33 UTC, terorie commented on libr/anal/dwarf_process.c
> +		R_LOG_WARN ("Warning: anal.dwarf.parse_type: infinite recursion detected.");
fixed all instances.

2022-06-27 21:57 UTC, trufae requested changes

2022-06-27 21:57 UTC, trufae commented on libr/core/canal.c
> +			R_LOG_WARN ("set your favourite calling convention in `e anal.cc=?`");
revert this line as it seems to break some tests. we will look later at them
```suggestion
			eprintf ("Warning: set your favourite calling convention in `e anal.cc=?`\n");
```

2022-06-27 21:57 UTC, trufae commented on libr/asm/asm.c
> +					R_LOG_ERROR ("Cannot assemble '%s' at line %d", ptr_start, linenum);
```suggestion
					eprintf ("Cannot assemble '%s' at line %d\n", ptr_start, linenum);
```

2022-06-27 21:57 UTC, trufae commented on libr/bin/p/bin_elf.inc
> +		R_LOG_WARN ("run r2 with -e bin.cache=true to fix relocations in disassembly");
```suggestion
		eprintf ("Warning: run r2 with -e bin.cache=true to fix relocations in disassembly\n");
```

2022-06-28 00:01 UTC, trufae commented on libr/anal/fcn.c
> +		R_LOG_WARN ("can't allocate such big bb of %"PFMT64d" bytes at 0x%08"PFMT64x"", (st64)size, addr);
```suggestion
		R_LOG_WARN ("can't allocate such big bb of %"PFMT64d" bytes at 0x%08"PFMT64x, (st64)size, addr);
```

2022-06-28 00:01 UTC, trufae commented on libr/anal/rtti_msvc.c
> +			R_LOG_WARN ("no td for col at 0x%"PFMT64x"", col->addr);
```suggestion
			R_LOG_WARN ("no td for col at 0x%"PFMT64x, col->addr);
```

2022-06-28 00:49 UTC, merged

2022-06-28 00:49 UTC, trufae commented
Thanks!