Remove global use for magic
radareorg/radare2 pull request #20447
Opened 2022-07-14 13:11 UTC by iotaaxel

- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

- The global variable was marked and moved. Will now use local static variable instead.

2022-07-14 13:58 UTC, trufae commented
local static is the same as global with a smaller scope. that doesn't solves the problem, the variables marked as R_TH_LOCAL are all global whatever context they are defined

2022-07-15 10:33 UTC, trufae requested changes
Remember not to remove the R_TH_LOCAL unless you can also remove the `static` so the global is gone

2022-07-15 10:33 UTC, trufae commented on libr/magic/apprentice.c
> +	if (done == NULL) {
```suggestion
	if (!done) {
```

2022-07-15 10:33 UTC, trufae commented on libr/magic/apprentice.c
> +	if (&done) {
```suggestion
	if (*done) {
```

2022-07-15 10:33 UTC, trufae commented on libr/magic/apprentice.c
> +	R_TH_LOCAL bool *done = NULL;
```suggestion
	bool done = false;
```

2022-07-15 10:33 UTC, trufae commented on libr/magic/apprentice.c
> +	init_file_tables (done);
```suggestion
	init_file_tables (&done);
```

2022-07-15 10:33 UTC, trufae commented on libr/magic/mdump.c
> +	static const char optyp[] = { FILE_OPS };
keep the R_TH_LOCAL. thats a global
```suggestion
	static R_TH_LOCAL const char optyp[] = { FILE_OPS };
```

2022-07-15 10:33 UTC, trufae commented on libr/magic/mdump.c
> +		static int daylight = 0;
```suggestion
		static R_TH_LOCAL int daylight = 0;
```

2022-07-15 10:33 UTC, trufae commented on libr/magic/mdump.c
> +		static time_t now = (time_t)0;
```suggestion
		static R_TH_LOCAL time_t now = (time_t)0;
```

2022-07-19 18:16 UTC, iotaaxel commented
I am getting some CI failure messages.

2022-07-20 12:07 UTC, trufae reviewed
.

2022-07-20 12:07 UTC, trufae commented on libr/magic/apprentice.c
> +		done = false;
please, use pointers properly. or at least check out the compiler warnings before commiting

2022-07-20 12:07 UTC, trufae commented on libr/magic/apprentice.c
> +	init_file_tables (&done);
that will initialize the tables everytime you call file_apprentice. the current implementation initalizes those tables only ONCE per thread and execution, which is not the same.

You should move this initialization into the r_magic_new() and then you can remove the init_file_tables() call inside the file_apprentice.

i have pusehd this change which superseeds this pr https://github.com/radareorg/radare2/pull/20474

2022-07-20 12:07 UTC, closed without merging