Add REL bin plugin (wip)
radareorg/radare2 pull request #20513
Opened 2022-07-30 09:09 UTC by terorie

- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

- [x] Section loading
- [x] Meson build
- [ ] Make build
- [ ] Internal relocs
- [ ] External relocs to ROM/symbols
- [ ] External relocs to PIC/imports
- [ ] Test DOL/REL linking
- [ ] Add license-compatible test

2022-07-31 13:30 UTC, trufae commented
[r] Cannot open '/Users/richard/prj/mkw/artifacts/orig/pal/StaticR.rel'
[53](https://github.com/radareorg/radare2/runs/7598718852?check_suite_focus=true#step:8:54)

send this file to this repo https://github.com/radareorg/radare2-testbins/pulls

2022-07-31 17:15 UTC, terorie commented on libr/bin/p/bin_rel.c
> +#include "../format/elf/glibc_elf.h"
no need to have this here

2022-08-01 08:31 UTC, terorie commented on test/db/formats/rel
> +            0x80555330      3bff0000       addi r31, r31, 0
relocs are completely missing here

2022-08-01 11:55 UTC, terorie commented on test/db/formats/rel
> +            0x80555330      3bff0000       addi r31, r31, 0
fixed with `-e io.cache=true`

2022-08-01 12:00 UTC, terorie commented
Ready for review, pending merge of https://github.com/radareorg/radare2-testbins/pull/78

2022-08-01 12:14 UTC, terorie commented
libFuzzer found something 🗡️ 

```
% r2 -F rel oom-3852cb7a9012f8d9f2f3c21ad599c97b1caee477
INFO: REL module ID 00000003
INFO: REL version 3

zsh: segmentation fault  r2 -F rel oom-3852cb7a9012f8d9f2f3c21ad599c97b1caee477
```

2022-08-01 12:33 UTC, terorie commented
Fixed OOM fuzz findings by adding limits to section/imp/reloc counts. Will let libFuzzer run for another hour or two

2022-08-07 14:28 UTC, trufae commented on test/db/formats/rel
> +ERROR: Imports from other REL (00000002) not yet implemented
this is a warning, if it was an error. it will not report anything after this message.

2022-08-07 14:28 UTC, trufae commented on test/db/formats/rel
> +ERROR: Imports from other REL (00000002) not yet implemented
lets say warning or debug or info, but not error

2022-08-07 14:29 UTC, trufae requested changes
wonder why the magic search is failing in this pr 🤔

2022-08-07 14:29 UTC, trufae commented
make it grin and ill merge

2022-08-17 22:40 UTC, trufae commented
ping

2022-08-19 11:39 UTC, trufae commented
Tired of waiting, i just fixed the crash and merged the thing. thanks!!

2022-08-19 11:39 UTC, closed without merging

2022-08-19 12:07 UTC, terorie commented
Apologies for the wait 😢 Will try to make it up with some backlogged tickets

2022-08-20 08:13 UTC, trufae commented
Np :D thanks for the contrib! It was just a tiny thing to get it in. I know its tedious to keep up with all the prs. So its ok for me to take over them