Init DAP protocol in IO plugin.
radareorg/radare2 pull request #20574
Opened 2022-08-14 02:05 UTC by gogo2464

- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

2022-08-15 11:21 UTC, trufae requested changes
supporting DAP will be a cool addition. you can see how other io-debug plugins work so you dont need to write a debug plugin to make it work as a backend. (just use the `e dbg.backend=io`)

2022-08-15 11:21 UTC, trufae commented on libr/io/p/io_dap.c
> +    return (strncmp(pathname, URI_PREFIX, strlen(URI_PREFIX)) == 0);
use tabs

2022-08-15 11:21 UTC, trufae commented on libr/io/p/io_dap.c
> +    return (strncmp(pathname, URI_PREFIX, strlen(URI_PREFIX)) == 0);
use r_str_startswith()

2022-08-15 11:21 UTC, trufae commented on libr/io/p/io_dap.c
> +    printf("%s\n", __func__);
remove debug printfs

2022-08-15 11:21 UTC, trufae commented on libr/io/p/io_dap.c
> +    if (!__plugin_open(io, pathname, 0))
use tabs and space before (

2022-08-15 11:21 UTC, trufae commented on libr/io/p/io_dap.c
> +    printf("%s\n", __func__);
remove log msg

2022-08-15 11:21 UTC, trufae commented on libr/io/p/io_dap.c
> +    RIOFoo *rio_foo = NULL;
initialize and assign in the same line after the if

2022-08-15 11:21 UTC, trufae commented on libr/io/p/io_dap.c
> +    if (!fd || !fd->data)
missing braces

2022-08-15 11:49 UTC, gogo2464 commented
I used this template: https://wenzel.github.io/2018/04/15/radare2-io-plugin-tutorial.html nothing is ready yet.

2022-10-06 11:03 UTC, trufae commented
the error:
```
'/home/runner/work/radare2/radare2/libr/parse/p'
[1451](https://github.com/radareorg/radare2/actions/runs/3196044580/jobs/5217456357#step:7:1452)
tcc: error: file '/home/runner/work/radare2/radare2/libr/../shlr/dap/lib/libgdbr.a' not found
[1452](https://github.com/radareorg/radare2/actions/runs/3196044580/jobs/5217456357#step:7:1453)
make[3]: *** [/home/runner/work/radare2/radare2/libr/..//libr/rules.mk:91: libr_io.so] Error 1
```

the problem

```
LDFLAGS+=$(SHLR)/dap/lib/libgdbr.$(EXT_AR)
```

2022-10-07 21:05 UTC, gogo2464 commented
@trufae fixed thank you so much!

For the other issues, this is just a template from internet. We could import the doc on r2book and r2 blog from https://wenzel.github.io/2018/04/15/radare2-io-plugin-tutorial.html and then update it.

2022-10-09 09:27 UTC, trufae commented
i cant repro the ptrace-attach problem you reported yesterday on the irc. the plugin is called and behaves as expected

2022-10-09 09:28 UTC, trufae commented
the failing linux-nocs job in the ci is because you are indenting with spaces instead of tabs. please run `sys/lint.sh` before commiting so you'll find some good hints to follow the coding style

2022-10-09 09:53 UTC, gogo2464 commented
> i cant repro the ptrace-attach problem you reported yesterday on the irc. the plugin is called and behaves as expected

I think I had untracked changes. Now that  git clone my own PR again from github, all seems fine.

2022-10-09 11:54 UTC, gogo2464 commented
> i cant repro the ptrace-attach problem you reported yesterday on the irc. the plugin is called and behaves as expected

I also used remote debuging from emulicious to test. Did you do so?

2023-02-12 10:12 UTC, gogo2464 commented on libr/io/p/io_dap.c
> +    printf("%s\n", __func__);
could I remove it in the future?

2024-02-17 23:38 UTC, closed without merging

2024-02-17 23:38 UTC, trufae commented
Closing this PR, after 2 years there is no relevant code in here, over time it got conflicts, so i think its better to close it

2024-02-17 23:48 UTC, gogo2464 commented
Yes sorry. I am very sorry :(