DWARF5 line header parsing
radareorg/radare2 pull request #21250
Opened 2023-01-15 03:40 UTC by MewtR

- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

My attempt to support DWARF5 line header parsing. Mostly done, just need to update the tests.

2023-01-15 18:51 UTC, trufae commented
Ready to review now? I didnt expect that pr and thats beautiful! 🥰

2023-01-15 22:51 UTC, MewtR commented
Thanks, yeah I think now it's fine. Let me know what you think.

2023-01-15 23:43 UTC, trufae commented
Fix those warnings
<img width="1033" alt="Screenshot 2023-01-16 at 00 43 13" src="https://user-images.githubusercontent.com/6431515/212573952-b9cfa442-bd84-4130-848f-7680ce8569f3.png">

2023-01-15 23:54 UTC, trufae requested changes
Will be good to do some fuzzing before merging this. I'm fine to merge it like this (but after 5.8.2) or do some fuzzing in `test/fuzz/` (see the readme to setup the thing). But the patch looks quite smaller than I expected. After addressing the comments i'll do another review. I can do some fuzzing on it if i find some time this week too. But having dwarf5 support was kind of high in the wishlist.

2023-01-15 23:54 UTC, trufae commented on libr/bin/dwarf.c
> +	RBinDwarfLineHeader *hdr, Sdb *sdb, int mode, PrintfCallback print) {
function signatures must be always 1 line for grepping purposes

2023-01-15 23:54 UTC, trufae commented on libr/bin/dwarf.c
> +
```suggestion
```

2023-01-15 23:54 UTC, trufae commented on libr/bin/dwarf.c
> +				hdr->file_names = calloc (sizeof (file_entry), total_entries);
check if calloc fails

2023-01-15 23:54 UTC, trufae commented on libr/bin/dwarf.c
> +	size_t maxlen = 0xfff;
```suggestion
	const size_t maxlen = 0xfff;
```

2023-01-15 23:54 UTC, trufae commented on libr/bin/dwarf.c
> +						// TODO handle this somehow
handle this case to avoid a crash.

2023-01-15 23:54 UTC, trufae commented on libr/bin/dwarf.c
> +			} else if (mode == R_MODE_PRINT && i == FILES) {
both cases use if (mode == R_MODE_PRINT. just group that like this:

```c
if (mode == R_MODE_PRINT) {
  switch (i) {
 case DIRECTORIES: 
  break;
case FILES:
 break;
}
```

2023-01-16 10:49 UTC, MewtR commented
I'll look into the fuzzing a little later this week.

2023-01-16 12:02 UTC, merged

2023-01-16 12:03 UTC, trufae commented
Let's merge it! i will have some time today to fuzz it and test it :) so it will fit into the release! thank you!