Another attempt to do EsilHooks ##esil
radareorg/radare2 pull request #21939
Opened 2023-06-19 09:45 UTC by condret

Maybe this time

Still a bit WIP

- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

2023-06-29 21:38 UTC, trufae requested changes
i like the way it works, but i think this introduces so many methods when we can make it much simpler by using a single function that takes operation as argument.

It's also very similar to how REvent works. maybe better to re-evaluate to improve this api that we dont use yet because we can have multiple event handlers around and that will be important for ranal too.

What do you think?

2023-06-29 21:38 UTC, trufae commented on libr/esil/esil.c
> +		r_esil_set_reg_write_imp (esil, (REsilImpHookRegWriteCB)internal_esil_reg_write_no_null, esil);
ideally the cast shuoldnt be needed, otherwise we can pass functions with different signature and get runtime crashes hard to debug

2023-06-29 21:38 UTC, trufae commented on libr/esil/esil_hooks.c
> +R_API bool r_esil_set_mem_write_imp(REsil *esil, REsilImpHookMemWriteCB imp, void *user) {
what about having only a set method and tell which event as argument, index those type of events in an fixed size array like esil->hooks[R_ESIL_EVENT_RR]..

2023-06-29 21:38 UTC, trufae commented on libr/esil/esil_hooks.c
> +		esil->hooks->mem_write_implementation = R_NEW (REsilHook);
uhm, only 1 handler per event? we cant have multiple listeners? that seems like not what we want right?

2023-06-29 21:38 UTC, trufae commented on libr/esil/esil_hooks.c
> +R_API void r_esil_del_reg_write_imp(REsil *esil) {
i would prefer to have a smaller API  and less functions, we want to do the ADD, DEL, CLEAR operations on RR,RW,MM,MW array of callbacks. this array of pointers can be an RVec, so they are executed in the right order and hold a void*user pointer. im thinking about something like this:

`esil.hook(ADD, MR, cb, user);`

ADD = enum for the supported operations: ADD, DEL, CLEAR, ..
MR = memory read, just another enum with other stuff
cb = the user provided callback for the given esil operation hook
user = user data pointer associated with the given callback

The cb is used as a uniqueid for each event, this is, you can `esil.hook(DEL, cb, NULL);`

At the end this is very similar to what REvent, what are the limitations you can think about it?

2024-08-04 10:56 UTC, trufae commented
ping, rebase for conflicts, and respond my comments pls

2024-11-14 19:39 UTC, condret commented
I'll look at this again in the next breaking

2024-12-03 21:02 UTC, trufae commented
can this PR be closed now?

2025-04-28 05:08 UTC, closed without merging