590 cleanups pt2
radareorg/radare2 pull request #22146
Opened 2023-08-11 15:01 UTC by luc-tielen

- [x] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

**Copilot**

2023-08-11 15:29 UTC, trufae commented
Red

2023-08-14 07:40 UTC, luc-tielen commented
I think it was red because I didn't do a full rebuild and one of the plugins wasn't migrated. Fixed now. 😄

2023-08-14 08:24 UTC, trufae requested changes

2023-08-14 08:24 UTC, trufae commented on libr/debug/p/debug_winkd.c
> -	if (strncmp (desc->plugin->name, "winkd", 6)) {
rstrstartswith()

2023-08-14 08:24 UTC, trufae commented on libr/core/cconfig.c
> -		if (core->io->desc->plugin->name && !strcmp (core->io->desc->plugin->name, "gdb")) {
better use R_UNWRAP once and reduce later dreferences

2023-08-14 09:05 UTC, merged