add '%' command to visual graph to search through disassembly and nav…
radareorg/radare2 pull request #22227
Opened 2023-09-07 23:11 UTC by lasek0

add '%' command in visual graph to search in disassemble and navigate to it. works with 'agfv' command

- [x] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

added search in visual graph, possible to search via assembly code, commens, variable names, etc.
in general this works as pdr~sentence amd read an address of that and s addr to navigate graph to found line

**Copilot**

2023-09-07 23:42 UTC, trufae requested changes
Wow! that looks like a really interesting way to navigate through the graph, I love it! check out my reviews

2023-09-07 23:42 UTC, trufae commented on libr/core/agraph.c
> +	r_core_cmd0 (core, "e scr.highlight=");
```suggestion
	r_config_set (core->config, "scr.highlight", "");
```

2023-09-07 23:42 UTC, trufae commented on libr/core/agraph.c
> +	if (core->cons->line->contents != NULL) {
free already checks for null

```suggestion
```

2023-09-07 23:42 UTC, trufae commented on libr/core/agraph.c
> +		free (core->cons->line->contents);
```suggestion
	free (core->cons->line->contents);
```

2023-09-07 23:42 UTC, trufae commented on libr/core/agraph.c
> +	}
```suggestion
```

2023-09-07 23:42 UTC, trufae commented on libr/core/agraph.c
> +			if (c == 'n') goto find_next;
missing braces {
}
```suggestion
			if (c == 'n') {
				goto find_next;
			}
```

2023-09-07 23:42 UTC, trufae commented on libr/core/agraph.c
> +		if (c == 'q') break;
```suggestion
		if (c == 'q') {
			break;
		}
```

2023-09-07 23:42 UTC, trufae commented on libr/core/agraph.c
> +					offset = offset_max-2;
```suggestion
					offset = offset_max - 2;
```

2023-09-07 23:42 UTC, trufae commented on libr/core/agraph.c
> +			printf ("Found (%d/%d) \"%s\". Press 'n' for next, 'N' for prev, 'q' for quit, any key other to conitnue", offset+1, offset_max, line);
Use r_cons_printf or R_LOG_INFO / R_LOG_WARN, but not `printf`

2023-09-07 23:42 UTC, trufae commented on libr/core/agraph.c
> +			printf ("Sentence \"%s\", not found. Press 'q' for quit, any key other to conitnue", buf);
same here

2023-09-07 23:42 UTC, trufae commented on libr/core/agraph.c
> +		fflush (stdout);
but maybe unnecessary

```suggestion
			r_cons_flush ();
```

2023-09-08 07:17 UTC, lasek0 commented
> 

Yes, I found this to be really usefull while working with graphs, so I decide to share it. Still this can be improved since searching in a graph block which is long, search does not navigate to middle of block but it navigate always to top of block instead (even if address is set [s addr] to proper line). However this is really usefull so it can be added I think as is.

2023-09-08 07:28 UTC, trufae commented
Fix the linting. Theres a missing space before (

2023-09-08 08:44 UTC, lasek0 commented
> Fix the linting. Theres a missing space before (

sorry do not see any more missing space

2023-09-08 13:39 UTC, merged

2023-09-08 13:39 UTC, trufae commented
Merged! thank you! that's a really handy feature