Fix symbol conflicts with libmagic
radareorg/radare2 pull request #22630
Opened 2024-02-20 16:18 UTC by meme

- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

The libmagic implementation that radare2 has contains symbols that conflict with the original libmagic, so rename all of the public symbols to have the `r_magic` prefix.

2024-02-22 18:43 UTC, trufae commented on libr/magic/file.h
> +R_IPI int r_magic_file_buffer(struct r_magic_set *, int, const char *, const void *, size_t);
use RMagic * instead of `struct r_magic_set`.. will be good to have some consistency across all those functions too

2024-02-22 18:44 UTC, trufae commented on shlr/sdb/src/buffer.c
> +void buffer_initialize(buffer *s, BufferOp op, int fd, char *buf, ut32 len) {
at some point this can cause some name conflict issues but this api shouldnt be public anyway.. but its fine to update it for now. thank you!

2024-02-22 18:44 UTC, trufae requested changes
.

2024-02-23 16:15 UTC, meme commented on libr/magic/file.h
> +R_IPI const char *r_magic_file_fmttime(unsigned int, int, char *);
We could also rename them to `magic_` instead of `r_magic`, maybe?

2024-02-23 17:48 UTC, trufae commented on libr/magic/file.h
> +R_IPI const char *r_magic_file_fmttime(unsigned int, int, char *);
magic_ is the original name from libmagic , so that will conflict with system library. thats why im suggesting __magic for the non-public apis

2024-02-27 15:22 UTC, merged