Rebase LE objects independently ##bin
radareorg/radare2 pull request #22764
Opened 2024-03-29 08:20 UTC by mrmacete

- [x] Mark this if you consider it ready to merge
- [x] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

This change introduces the optional environment variable `R_LE_BASES` which can contain a `:`-separated list of addresses where the base of each defined object should be. This can be used to easily match the same memory layout as a running DOS system can have while debugging.

The env variable is not great, but it's needed since each object is rebased independently, instead of "rigidly translated" like is more common on modern systems where the existing concept of a single base address would suffice.

2024-03-29 18:07 UTC, trufae commented
if you want to go for the env var appraoch i would suggest to prefix it as RABIN2_ instead (this is from rabin2 -h) but maybe this feature makes sense to be used by other multibin binaries like ar, jar, multidex, .. im happy to merge it like this but if we need to break the abi i would prefer to do it asap before 5.9

<img width="1542" alt="Screenshot 2024-03-29 at 19 04 29" src="https://github.com/radareorg/radare2/assets/6431515/00aa980d-fe48-4e7d-8c33-e5eb3d061da8">

2024-03-30 10:42 UTC, trufae commented
So my proposal would be:

* Use RABIN2_LE_BASES instead of R_LE_BASES
* Make this concept "global" for all fileformats via config var and a field in a struct, etc

Any of those options are valid to me, probably the first one is fine for a quick merge.

2024-03-30 10:44 UTC, trufae commented on libr/bin/format/le/le.c
> +	char * bases_raw = r_sys_getenv ("R_LE_BASES");
```suggestion
	char * bases_raw = r_sys_getenv ("RABIN2_LE_BASES");
```

2024-03-30 10:44 UTC, trufae requested changes
.

2024-03-30 14:40 UTC, mrmacete commented
> So my proposal would be:
> 
> * Use RABIN2_LE_BASES instead of R_LE_BASES
> * Make this concept "global" for all fileformats via config var and a field in a struct, etc
> 
> Any of those options are valid to me, probably the first one is fine for a quick merge.

agree! let's rename for now, the better solution would be a global concept but requires more discussion and more work which requires time and can be done after the release 🙌

2024-03-30 15:33 UTC, merged

2024-03-30 15:33 UTC, trufae commented
Looks good!