Add info about single module recompilation ##doc
radareorg/radare2 pull request #23114
Opened 2024-07-10 18:32 UTC by satk0

- [x] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

2024-07-10 18:42 UTC, trufae commented on DEVELOPERS.md
> +Huge increase in recompilation speed could also be achieved by recompilating only modified modules (directories) by using:
```suggestion
it is not necessary to recompile the whole project everytime. Just run make in the directory you are working on to compile these parts only by using:
```

2024-07-10 18:42 UTC, trufae requested changes
What about sthg like this?

2024-07-10 19:49 UTC, trufae commented
yeah, also mention that symlink thing :) it will be clearer. thanks

2024-07-11 11:57 UTC, satk0 commented
Done. Let me know how it looks

2024-07-11 12:24 UTC, merged