added registers xmm0 to xmm15 while debugging under FreeBSD.
radareorg/radare2 pull request #23429
Opened 2024-10-06 13:38 UTC by rolio37

- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

added xmm0 to xmm15 registers while debugging under FreeBSD.

2024-10-06 18:05 UTC, trufae requested changes
.

2024-10-06 18:05 UTC, trufae commented on libr/debug/p/debug_native.c
> +
```suggestion
```
No empty lines

2024-10-06 18:05 UTC, trufae commented on libr/debug/p/debug_native.c
> +                ret = ptrace(PT_GETXSTATE, pid,  (caddr_t)buf, info.xsave_len);
```suggestion
                ret = ptrace (PT_GETXSTATE, pid,  (caddr_t)buf, info.xsave_len);
```

space before (

2024-10-06 18:05 UTC, trufae commented on libr/debug/p/debug_native.c
> +              #endif
```suggestion
              #endif
```

dont indent preprocessor directives

2024-10-06 18:05 UTC, trufae commented on libr/debug/p/debug_native.c
> +               break;
do not indent with spaces. We use tabs

2024-10-06 18:05 UTC, trufae commented on libr/debug/p/native/bsd/bsd_debug.c
> +               {
Braces must be opened in the same line as the if

2024-10-06 19:37 UTC, trufae commented
Linting not fixed yet. Run the sys/lint.sh script

2024-10-06 20:35 UTC, trufae commented on libr/debug/p/debug_native.c
> +		ret = ptrace(PT_GETXSTATE_INFO, pid, (caddr_t)&info, sizeof (info));
Space before (

2024-10-06 20:35 UTC, trufae commented on libr/debug/p/native/bsd/bsd_debug.c
> +		r = ptrace(PT_GETXSTATE_INFO, dbg->pid, (caddr_t)&info, sizeof (info));
Same

2024-10-06 20:35 UTC, trufae commented on libr/debug/p/native/bsd/bsd_debug.c
> +			r = ptrace(PT_SETXSTATE, dbg->pid,  (caddr_t)buf, info.xsave_len);
```suggestion
			r = ptrace(PT_SETXSTATE, dbg->pid, (caddr_t)buf, info.xsave_len);
```

2024-10-06 20:36 UTC, trufae commented on libr/debug/p/native/bsd/bsd_debug.c
> +		#endif
Do not indent this. The # must be at column 0

2024-10-06 20:36 UTC, trufae requested changes
.

2024-10-06 23:44 UTC, merged

2024-10-07 14:38 UTC, rolio37 commented
Hi, thanks for your patience.