Check data APIs nullability for #23490
radareorg/radare2 pull request #23635
Opened 2024-11-13 11:20 UTC by astralia

- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

2024-11-13 11:20 UTC, astralia commented on libr/anal/data.c
> +	R_RETURN_VAL_IF_FAIL (t == R_ANAL_DATATYPE_NULL, NULL);
I’m not sure if this check should be done this way…

2024-11-13 17:52 UTC, trufae requested changes
asdasdfasdf

2024-11-13 17:52 UTC, trufae commented on libr/anal/data.c
>  R_API const char *r_anal_datatype_tostring(RAnalDataType t) {
```suggestion
R_API R_NULLABLE const char *r_anal_datatype_tostring(RAnalDataType t) {
```

2024-11-13 17:52 UTC, trufae commented on libr/anal/data.c
> +	R_RETURN_VAL_IF_FAIL (t == R_ANAL_DATATYPE_NULL, NULL);
```suggestion
```

2024-11-13 17:52 UTC, trufae commented on libr/anal/data.c
>  	case R_ANAL_DATATYPE_ARRAY:
```suggestion
	case R_ANAL_DATATYPE_NULL:
		return "null";
	case R_ANAL_DATATYPE_ARRAY:
```

2024-11-13 17:52 UTC, trufae commented on libr/anal/data.c
> +	default:
```suggestion
```

2024-11-13 17:52 UTC, trufae commented on libr/anal/data.c
> +		break;
```suggestion
```

2024-11-14 23:44 UTC, trufae commented on libr/anal/data.c
> +		return "null";
```suggestion
		return NULL;
```

2024-11-15 05:31 UTC, merged